objects/Account.object
<CustomObject>
    <fields>
        <fullName>Accounting_Finance_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Accounting Finance Book</label>
        <referenceTo>blng__FinanceBook__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Legal_Entity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Entity</label>
        <referenceTo>blng__LegalEntity__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__BillToContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bill To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/blng__FinanceBook__c.object
<CustomObject>
    <fields>
        <fullName>blng__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>If Inactive, new transactions can be recorded into this Finance Book but does not affect those transactions already in the book</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>blng__PeriodType__c</fullName>
        <inlineHelpText>&quot;Used to classify Finance Books. Can be:
Revenue
Accounting&quot;</inlineHelpText>
        <label>Period Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__FinanceBookPeriodType</valueSetName>
        </valueSet>
    </fields>
    <label>Finance Book</label>
    <nameField>
        <label>Finance Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/blng__LegalEntity__c.object
<CustomObject>
    <fields>
        <fullName>blng__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Changing from Active to Inactive will not affect existing transactions or assignments.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Kodiak_AccountBillingSetupController.cls
public with sharing class Kodiak_AccountBillingSetupController { 

    @AuraEnabled
    public static Boolean showAlert(Id recordId){
        Account thisAccount = [SELECT 
                                    Id,
                                    Accounting_Finance_Book__c,
                                    Legal_Entity__c,
                                    blng__BillToContact__c
                                FROM Account
                                WHERE Id = :recordId];
        if(thisAccount.Accounting_Finance_Book__c == null || thisAccount.Legal_Entity__c == null || thisAccount.blng__BillToContact__c == null) {
            System.debug('Missing Account Finance Book, Legal Entity, or Bill To Contact');
            return true;
        }
        System.debug('Account has Finance Book, Legal Entity, and Bill To Contact');
        return false;
    }

    @AuraEnabled
    public static Account getAccountDetails(Id recordId){
        system.debug('Alex Account Record ID:' + recordId);
        Account thisAccount = [SELECT 
                                    Id,
                                    Accounting_Finance_Book__c,
                                    Accounting_Finance_Book__r.Name,
                                    Legal_Entity__c,
                                    Legal_Entity__r.Name,
                                    blng__BillToContact__c,
                                    blng__BillToContact__r.Name
                                FROM Account
                                WHERE Id = :recordId];
                                return thisAccount;
    }

    @AuraEnabled
    public static List<blng__LegalEntity__c> getLegalEntities(){
        return [SELECT 
                    Id,
                    Name,
                    blng__Active__c
                FROM blng__LegalEntity__c
                WHERE blng__Active__c = true];
    }

    @AuraEnabled
    public static List<blng__FinanceBook__c> getFinanceBooks(){
        return [SELECT 
                    Id,
                    Name,
                    blng__Active__c,
                    blng__PeriodType__c
                FROM blng__FinanceBook__c
                WHERE blng__Active__c = true
                AND blng__PeriodType__c = 'Accounting'];
    }

    @AuraEnabled
    public static List<Contact> getBillToContacts(Id recordId){
        System.debug('getBillToContacts: recordId = ' + recordId);
        return [SELECT 
                    Id, 
                    AccountId,
                    Name
                FROM Contact
                WHERE AccountId = :recordId]; // hardcoded for now...WHERE AccountId = '0013c00001rTZQ8AAO'
    }

    @AuraEnabled
    public static void saveAccountBilling(Id recordId, Id legalEntityId, Id financeBookId, Id billToContactId){
        Account thisAccount = [SELECT 
                                    Id,
                                    Accounting_Finance_Book__c,
                                    Legal_Entity__c,
                                    blng__BillToContact__c
                                FROM Account
                                WHERE Id = :recordId];

        if(legalEntityId != null) {
            thisAccount.Legal_Entity__c = legalEntityId;
        }

        if(financeBookId != null) {
            thisAccount.Accounting_Finance_Book__c = financeBookId;
        }

        if(billToContactId != null) {
            thisAccount.blng__BillToContact__c = billToContactId;
        }

        try {
            Database.update(thisAccount);
        } catch (DmlException e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}