objects/Approval_Threshold__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Level__c</fullName>
        <label>Approval Level</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lower_Bound_Percent__c</fullName>
        <label>Lower Bound</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Approval Thresholds</relationshipLabel>
        <relationshipName>Approval_Thresholds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Upper_Bound_Percent__c</fullName>
        <label>Upper Bound</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Approval Threshold</label>
    <nameField>
        <displayFormat>Z-{00000}</displayFormat>
        <label>Approval Threshold Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approval Thresholds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Q2CeditTiers.cls
public class Q2CeditTiers {
    public Product2 Prod;
    public Approval_Threshold__c del;
    public List < Approval_Threshold__c > addThreshList { get; set; }
    public List < Approval_Threshold__c > delThreshList { get; set; }
    public List < Approval_Threshold__c > ThreshList { get; set; }
    public Integer totalCount { get; set; }
    public Integer rowIndex { get; set; }
    public List < Approval_Threshold__c > delThreshs { get; set; }

    public Q2CeditTiers(ApexPages.StandardController controller) {
        Prod = (Product2) controller.getRecord();
        ThreshList = [SELECT Id, Approval_Level__c, Lower_Bound_Percent__c, Product__c, Upper_Bound_Percent__c FROM Approval_Threshold__c WHERE Product__c = :Prod.Id];
        totalCount = ThreshList.size();
        delThreshList = new List < Approval_Threshold__c >();
        delThreshs = new List < Approval_Threshold__c >();
    }

    public void addRow() {
        addThreshList = new List < Approval_Threshold__c >();
        ThreshList.add(new Approval_Threshold__c(Product__c = Prod.Id));
    }

    public PageReference save() {
        upsert ThreshList;
        delete delThreshList;
        //return (new ApexPages.StandardController(Prod)).view();
        PageReference pageRef = new PageReference('/' + Prod.Id);
        pageRef.getParameters().put('id', Prod.Id);
        return pageRef;
    }
    public void deleteRow() {
        rowIndex = Integer.valueOf(ApexPages.currentPage().getParameters().get('rowIndex'));
        del = ThreshList.remove(rowIndex);
        delThreshList.add(del);
    }
}