objects/blng__FinanceBook__c.object
<CustomObject>
    <fields>
        <fullName>blng__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>If Inactive, new transactions can be recorded into this Finance Book but does not affect those transactions already in the book</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>blng__PeriodType__c</fullName>
        <inlineHelpText>&quot;Used to classify Finance Books. Can be:
Revenue
Accounting&quot;</inlineHelpText>
        <label>Period Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__FinanceBookPeriodType</valueSetName>
        </valueSet>
    </fields>
    <label>Finance Book</label>
    <nameField>
        <label>Finance Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/blng__FinancePeriod__c.object
<CustomObject>
    <fields>
        <fullName>blng__FinanceBook__c</fullName>
        <label>Finance Book</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>blng__FinanceBook__c.blng__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>blng__FinanceBook__c</referenceTo>
        <relationshipLabel>Finance Periods</relationshipLabel>
        <relationshipName>FinancePeriods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>blng__LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance Period Legal Entity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>blng__LegalEntity__c.blng__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>blng__LegalEntity__c</referenceTo>
        <relationshipLabel>Finance Periods</relationshipLabel>
        <relationshipName>FinancePeriods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__PeriodEndDate__c</fullName>
        <label>Period End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>blng__PeriodStartDate__c</fullName>
        <label>Period Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>blng__PeriodStatus__c</fullName>
        <label>Period Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__FinancialPeriodStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>blng__PeriodType__c</fullName>
        <formula>Text(blng__FinanceBook__r.blng__PeriodType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Period Type</label>
        <type>Text</type>
    </fields>
    <label>Finance Period</label>
    <nameField>
        <label>Financial Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/blng__LegalEntity__c.object
<CustomObject>
    <fields>
        <fullName>blng__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Changing from Active to Inactive will not affect existing transactions or assignments.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>blng__City__c</fullName>
        <inlineHelpText>City Name</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>blng__Country__c</fullName>
        <inlineHelpText>Country Name</inlineHelpText>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>blng__County__c</fullName>
        <inlineHelpText>County Name</inlineHelpText>
        <label>County</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>blng__LegalEntityNumber__c</fullName>
        <displayFormat>LE-{00000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>System generated. A unique number for this Legal Entity record.</inlineHelpText>
        <label>Legal Entity Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>blng__State__c</fullName>
        <inlineHelpText>State Name</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>blng__Street1__c</fullName>
        <inlineHelpText>Primary Street Address</inlineHelpText>
        <label>Street 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>blng__ZipPostalCode__c</fullName>
        <inlineHelpText>ZIP or Postal Code</inlineHelpText>
        <label>Zip / Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/blng__FinancialPeriodStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Close</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Opened</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Open</fullName>
    </customValue>
    <masterLabel>Financial Period Status</masterLabel>
</GlobalValueSet>

classes/AccountingPeriodModCtrl.cls
public class AccountingPeriodModCtrl {
      
    @AuraEnabled  
	public static List <blng__FinancePeriod__c> getAccountingPeriods() {
    	return [SELECT Id, name, blng__FinanceBook__r.Name, blng__LegalEntity__r.Name , blng__PeriodType__c , blng__PeriodStartDate__c , blng__PeriodEndDate__c, blng__PeriodStatus__c FROM blng__FinancePeriod__c WHERE blng__PeriodType__c = 'Accounting' AND CurrencyIsoCode = 'USD' AND blng__PeriodStartDate__c > LAST_YEAR AND blng__LegalEntity__r.Name LIKE '%US%' ORDER BY blng__PeriodStartDate__c ASC LIMIT 12];
    }
    
    @AuraEnabled
    public static List <blng__FinancePeriod__c> getRevenuePeriods() {
        return [SELECT Id, name, blng__FinanceBook__r.Name, blng__LegalEntity__r.Name , blng__PeriodType__c , blng__PeriodStartDate__c , blng__PeriodEndDate__c, blng__PeriodStatus__c FROM blng__FinancePeriod__c WHERE blng__PeriodType__c = 'Revenue' AND CurrencyIsoCode = 'USD' AND blng__PeriodStartDate__c > LAST_YEAR AND blng__LegalEntity__r.Name LIKE '%US%' ORDER BY blng__PeriodStartDate__c ASC LIMIT 6];
    }
    
    @AuraEnabled
    public static List <blng__FinanceBook__c > getDemBooks() {
        return [SELECT Id, name, blng__PeriodType__c FROM blng__FinanceBook__c WHERE blng__Active__c  = true ORDER BY blng__PeriodType__c DESC];
    }
    
    @AuraEnabled
    public static List <blng__LegalEntity__c> getDemEntities() {
        return [SELECT Id, Name, blng__LegalEntityNumber__c, blng__Street1__c, blng__City__c, blng__County__c, blng__State__c, blng__Country__c, blng__ZipPostalCode__c FROM blng__LegalEntity__c WHERE blng__Active__c  = true];
    }
    
}