objects/blng__Usage__c.object
<CustomObject>
    <label>Usage</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Usage #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SBQQ__ChargeType__c</fullName>
        <description>The type of the product charge.</description>
        <inlineHelpText>The type of the product charge.</inlineHelpText>
        <label>Charge Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>SBQQ__ChargeType</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Q2CUsageUploader.cls
public class Q2CUsageUploader {

/**
* Create a new Usage Record
*
*/
    @AuraEnabled
    public static void createRecord(blng__Usage__c usageRecord) {

        try {
            System.debug('CreateCandidateRecord::createRecord::usageRecord' + usageRecord);

            if (usageRecord != null) {
                insert usageRecord;
            }
        } catch (Exception ex) {
        }
    }
    
/**
* Pull up all related product orders for picklist
*
*/
	@AuraEnabled
    public static Order fetchRelatedOrderItems(String orderId) {
        return [SELECT Id, (SELECT Id, OrderItemNumber , Order.Account.Name, Order.Account.AccountNumber, Product2Id, Product2.Name FROM OrderItems WHERE SBQQ__ChargeType__c = 'Usage') FROM Order WHERE Id = :orderId];
    }
}