objects/blng__InvoiceScheduler__c.object
<CustomObject>
    <customHelpPage>blng__InvoiceSchedulerHelp</customHelpPage>
    <fields>
        <fullName>blng__InvoiceBatches__c</fullName>
        <label>Invoice Batch</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__InvoiceBatch</valueSetName>
        </valueSet>
    </fields>
    <label>Invoice Scheduler</label>
    <nameField>
        <label>Invoice Scheduler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Schedulers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>blng__InvoiceBatch__c</fullName>
        <label>Invoice Batch</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__InvoiceBatch</valueSetName>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

globalValueSets/blng__InvoiceBatch.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Batch 1</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 2</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 3</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 4</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 5</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 6</fullName>
    </customValue>
    <customValue>
        <fullName>Declined</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 7</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 8</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 9</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 10</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 11</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 12</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 13</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 14</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 15</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 16</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 17</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 18</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 19</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 20</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 21</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 22</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 23</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 24</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 25</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 26</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 27</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 28</fullName>
    </customValue>
    <customValue>
        <fullName>Batch 29</fullName>
    </customValue>
    <masterLabel>Invoice Batch</masterLabel>
</GlobalValueSet>

classes/SetInvoiceBatch2.cls
public class SetInvoiceBatch2 {
  @InvocableMethod(label='SetInvoiceBatch Invoice Scheduler' description='SetInvoiceBatch INV')
  public static List<blng__InvoiceScheduler__c> SetInvoiceBatchNow(List<ID> ids) {
    List<blng__InvoiceScheduler__c> ords = [SELECT Id,blng__InvoiceBatches__c FROM blng__InvoiceScheduler__c WHERE Id in :ids];
    Schema.DescribeFieldResult F = Order.blng__InvoiceBatch__c.getDescribe();
    Schema.sObjectField T = F.getSObjectField();
    List<PicklistEntry> picklistentries = T.getDescribe().getPicklistValues();
    List<String> entries = new List<String>();
    
    for(PicklistEntry PLE : picklistentries){
    
        entries.add(PLE.getValue());
    
    }
    
    String Batch = 'Batch 6';
    String Alias = [Select Id, Alias from User WHERE Id = :Userinfo.getUserId()].Alias;

    if(entries.contains(Alias)){
      Batch = Alias;
    }
    for (blng__InvoiceScheduler__c ord : ords) {
        ord.blng__InvoiceBatches__c = Batch;
    }
    update Ords;
    return ords;
  }
}