objects/blng__FinanceBook__c.object
<CustomObject>
    <fields>
        <fullName>blng__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>If Inactive, new transactions can be recorded into this Finance Book but does not affect those transactions already in the book</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>blng__Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>blng__PeriodType__c</fullName>
        <inlineHelpText>&quot;Used to classify Finance Books. Can be:
Revenue
Accounting&quot;</inlineHelpText>
        <label>Period Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__FinanceBookPeriodType</valueSetName>
        </valueSet>
    </fields>
    <label>Finance Book</label>
    <nameField>
        <label>Finance Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/blng__FinancePeriod__c.object
<CustomObject>
    <fields>
        <fullName>blng__FinanceBook__c</fullName>
        <label>Finance Book</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>blng__FinanceBook__c.blng__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>blng__FinanceBook__c</referenceTo>
        <relationshipLabel>Finance Periods</relationshipLabel>
        <relationshipName>FinancePeriods</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>blng__LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance Period Legal Entity</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>blng__LegalEntity__c.blng__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>blng__LegalEntity__c</referenceTo>
        <relationshipLabel>Finance Periods</relationshipLabel>
        <relationshipName>FinancePeriods</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>blng__PeriodEndDate__c</fullName>
        <label>Period End Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>blng__PeriodStartDate__c</fullName>
        <label>Period Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>blng__PeriodStatus__c</fullName>
        <label>Period Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__FinancialPeriodStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>blng__PeriodType__c</fullName>
        <formula>Text(blng__FinanceBook__r.blng__PeriodType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Period Type</label>
        <type>Text</type>
    </fields>
    <label>Finance Period</label>
    <nameField>
        <label>Financial Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Finance Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/blng__LegalEntity__c.object
<CustomObject>
    <fields>
        <fullName>blng__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Changing from Active to Inactive will not affect existing transactions or assignments.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>blng__City__c</fullName>
        <inlineHelpText>City Name</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>blng__Country__c</fullName>
        <inlineHelpText>Country Name</inlineHelpText>
        <label>Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>blng__Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>blng__State__c</fullName>
        <inlineHelpText>State Name</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Legal Entity</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/blng__PaymentGateway__c.object
<CustomObject>
    <description>Configuration object. The administrator should create one Account for the appropriate Payment Gateway.</description>
    <fields>
        <fullName>adnblng__APILoginId__c</fullName>
        <label>APILoginId</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>adnblng__APITransactionKey__c</fullName>
        <label>APITransactionKey</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>adnblng__TestMode__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TestMode</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>blng__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>blng__Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>blng__GatewayType__c</fullName>
        <label>Gateway Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__GatewayType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>blng__Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>csblng__MerchantId__c</fullName>
        <label>MerchantId</label>
        <length>128</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>csblng__MerchantReference__c</fullName>
        <label>MerchantReference</label>
        <length>128</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>csblng__TestMode__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TestMode</label>
        <type>Checkbox</type>
    </fields>
    <label>Payment Gateway</label>
    <nameField>
        <label>Payment Gateway Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Gateways</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/blng__RevenueDistributionMethod__c.object
<CustomObject>
    <customHelpPage>blng__revenueDistributionHelp</customHelpPage>
    <fields>
        <fullName>blng__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Revenue Distribution Method</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Distribution Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/blng__RevenueRecognitionRule__c.object
<CustomObject>
    <fields>
        <fullName>blng__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Revenue Recognition Rule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Recognition Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/blng__RevenueRecognitionTreatment__c.object
<CustomObject>
    <fields>
        <fullName>blng__Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>blng__FlatAmount__c</fullName>
        <label>Flat Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Revenue Recognition Treatment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Revenue Recognition Treatments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/blng__RevenueSchedule__c.object
<CustomObject>
    <customHelpPage>blng__revenueScheduleHelp</customHelpPage>
    <fields>
        <fullName>blng__LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Lookup to the Legal Entity where this Revenue will be recorded.</inlineHelpText>
        <label>Revenue Legal Entity</label>
        <referenceTo>blng__LegalEntity__c</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>RevenueSchedules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__RevenueRecognitionTreatment__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Lookup to the Revenue Treatment used to define this Revenue Schedule</inlineHelpText>
        <label>Revenue Recognition Treatment</label>
        <referenceTo>blng__RevenueRecognitionTreatment__c</referenceTo>
        <relationshipLabel>Revenue Schedules</relationshipLabel>
        <relationshipName>RevenueRecognitionTreaRevenueSchedules</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Revenue Schedule</label>
    <nameField>
        <displayFormat>RS-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/blng__RevenueTransaction__c.object
<CustomObject>
    <customHelpPage>blng__revenueTransactionHelp</customHelpPage>
    <fields>
        <fullName>blng__LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Entity</label>
        <referenceTo>blng__LegalEntity__c</referenceTo>
        <relationshipLabel>RevenueTransactions</relationshipLabel>
        <relationshipName>LegalEntityRevenueTransactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__RevenueRecognitionTreatment__c</fullName>
        <inlineHelpText>Inherited from the Revenue Schedule. The Revenue Treatment that is used to calculate this transaction</inlineHelpText>
        <label>Revenue Recognition Treatment</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Revenue Transaction</label>
    <nameField>
        <displayFormat>RT-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revenue Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/blng__TaxRate__c.object
<CustomObject>
    <description>Holds the VAT/Tax rates, codes, zones etc</description>
    <fields>
        <fullName>blng__AddressComparison__c</fullName>
        <externalId>true</externalId>
        <label>Address Comparison</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>blng__City__c</fullName>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>blng__Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__BillingCountry</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>blng__LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Entity</label>
        <referenceTo>blng__LegalEntity__c</referenceTo>
        <relationshipLabel>Tax Rates</relationshipLabel>
        <relationshipName>LegalEntityTaxRates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__PriorityAddressComparison__c</fullName>
        <label>Priority Address Comparison</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>blng__Priority__c</fullName>
        <label>Priority</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>blng__TaxRatePriority</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>blng__Rate__c</fullName>
        <label>Rate</label>
        <precision>18</precision>
        <required>true</required>
        <scale>4</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>blng__State__c</fullName>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>blng__TaxCode__c</fullName>
        <label>Tax Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>blng__ZipCode__c</fullName>
        <label>Zip Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Tax Rate</label>
    <nameField>
        <label>Tax Identifier</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

globalValueSets/blng__BillingCountry.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antarctica</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaidjan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia-Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>Bouvet Island</fullName>
    </customValue>
    <customValue>
        <fullName>Brazil</fullName>
    </customValue>
    <description>Billing Country</description>
    <masterLabel>Billing Country</masterLabel>
</GlobalValueSet>

globalValueSets/blng__FinancialPeriodStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Open</fullName>
    </customValue>
    <customValue>
        <fullName>Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Close</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Closed</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Opened</fullName>
    </customValue>
    <customValue>
        <fullName>Pending Open</fullName>
    </customValue>
    <masterLabel>Financial Period Status</masterLabel>
</GlobalValueSet>

globalValueSets/blng__GatewayType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>CyberSource</fullName>
    </customValue>
    <customValue>
        <fullName>AuthorizeDotNet</fullName>
    </customValue>
    <customValue>
        <fullName>Payeezy</fullName>
    </customValue>
    <customValue>
        <fullName>PayFlowPro</fullName>
    </customValue>
    <customValue>
        <fullName>MockGateway</fullName>
        <default>true</default>
        <label>SmartBytes Payment Gateway</label>
    </customValue>
    <masterLabel>Gateway Type</masterLabel>
</GlobalValueSet>

classes/Q2CinitBilling.cls
public class Q2CinitBilling {
    public static void initBill() {
        CPQB_RecordReset.disableBillingTriggers(true);
        //deleteRevenueSchedules();
        deleteFinancePeriods();
        CPQB_RecordReset.disableBillingTriggers(false);
        //clearit();
        //System.enqueueJob(new DeleteRecords());
        createFinancePeriods();
        createRevenueTreatments();
        resetPG();
        resetTR();
    }
    
    public static void purgeBillingData() { // ALEX!!!!!!
        //CPQB_RecordReset.disableBillingTriggers(true);
        // delete revenue transactions...
        BatchRTRecordDelete delRT = new BatchRTRecordDelete(); 
		Id batchId = Database.executeBatch(delRT, 10000);
        // delete revenue schedules();
        BatchRSRecordDelete delRS = new BatchRSRecordDelete(); 
		Id batchId2 = Database.executeBatch(delRS, 10000);
    }

    @future
    public static void resetPG() {
        List<blng__PaymentGateway__c> PGs = [SELECT 
                                                   adnblng__APILoginId__c, 
                                                   adnblng__APITransactionKey__c, 
                                                   csblng__MerchantId__c, 
                                                   csblng__MerchantReference__c, 
                                                   blng__GatewayType__c, 
                                                   blng__Default__c, 
                                                   csblng__TestMode__c, 
                                                   adnblng__TestMode__c
                                             FROM blng__PaymentGateway__c 
                                             WHERE Name = 'CyberSource'];
        for (blng__PaymentGateway__c pg : PGs) {
            if ((pg.blng__GatewayType__c == 'CyberSource') && (pg.csblng__TestMode__c == TRUE)) {
                pg.csblng__MerchantId__c = 'salesforcebilling';
                pg.csblng__MerchantReference__c = 'salesforcebilling';
                pg.blng__Default__c = FALSE;
            } else if (pg.blng__GatewayType__c == 'AuthorizeDotNet' && (pg.adnblng__TestMode__c == TRUE)) {
                pg.adnblng__APILoginId__c = '3y33JXnnN5Z4';
                pg.adnblng__APITransactionKey__c = '57zJ2sG376mXkRqf';
                pg.blng__Default__c = FALSE;
            } else if (pg.blng__GatewayType__c == 'MockGateway') {
                pg.blng__Active__c = TRUE;
                pg.blng__Default__c = TRUE;
            }
        }
        update PGs;
    }

    //tax treatments
    @future
    public static void resetTR() {
        List<blng__TaxRate__c> NewTRs = new List<blng__TaxRate__c>();
        List<blng__TaxRate__c> OldTRs = [SELECT 
                                               Name, blng__State__c, 
                                               blng__City__c, 
                                               blng__ZipCode__c, 
                                               blng__Country__c, 
                                               blng__Priority__c, 
                                               blng__TaxCode__c, 
                                               blng__Rate__c, 
                                               blng__LegalEntity__c
                                         FROM blng__TaxRate__c ];
        for (Integer i = 0; i < OldTRs.size(); i++) {
            blng__TaxRate__c NewTR = OldTRs.get(i).clone(false, true);
            NewTR.blng__AddressComparison__c = NewTR.blng__Country__c + '----' + NewTR.blng__TaxCode__c + '-' + NewTR.blng__LegalEntity__c;
            NewTR.blng__PriorityAddressComparison__c = NewTR.blng__Priority__c + '-' + NewTR.blng__Country__c + '----' + NewTR.blng__TaxCode__c + '-' + NewTR.blng__LegalEntity__c;
            NewTRs.add(NewTR);
        }
        delete OldTRs;
        insert NewTRs;
    }

    //Finance Periods
    public static void createFinancePeriods() {
        List<CurrencyType> currencies = [SELECT 
                                               ConversionRate, 
                                               DecimalPlaces, 
                                               IsCorporate, 
                                               IsoCode
                                         FROM CurrencyType
                                         WHERE IsActive = TRUE];
        Integer mutableYear, mutableMonth;
        Date periodStart, periodEnd;
        List<blng__FinancePeriod__c> fpToInsert = new List<blng__FinancePeriod__c>();
        List<blng__LegalEntity__c> allLegalEntities = [SELECT 
                                                             Id, 
                                                             Name
                                                       FROM blng__LegalEntity__c ];
        Date todayDate = Date.today();
        Integer monthZero = 1;
        //Integer monthZero = todayDate.month();
        Integer yearZero = todayDate.year();
        Map<Integer, String> monthNameMap = new Map<Integer, String>{1 => 'Jan', 2 => 'Feb', 3 => 'Mar', 4 => 'Apr', 5 => 'May', 6 => 'Jun', 7 => 'Jul', 8 => 'Aug', 9 => 'Sep', 10 => 'Oct', 11 => 'Nov', 12 => 'Dec'};

        for (blng__FinanceBook__c fb : [SELECT 
                                              Id, 
                                              Name, blng__PeriodType__c
                                        FROM blng__FinanceBook__c ]) {
            for (blng__LegalEntity__c le : allLegalEntities) {
                for (CurrencyType curr : currencies) {
                    for (Integer i = 0; i < 48; i++) {
                        if (i == 0) {
                            periodStart = Date.newInstance(yearZero, monthZero, 1);
                            periodEnd = Date.newInstance(yearZero, monthZero, Date.daysInMonth(yearZero, monthZero));
                        } else {
                            periodStart = periodStart.addMonths(1);
                            mutableYear = periodStart.year();
                            mutableMonth = periodStart.month();
                            periodEnd = Date.newInstance(mutableYear, mutableMonth, Date.daysInMonth(mutableYear, mutableMonth));

                        }
                        //blng__FinancePeriod__c fp = new blng__FinancePeriod__c(Name = monthNameMap.get(periodStart.month())+' ' + String.valueOf(periodStart.year())+'-' + fb.blng__PeriodType__c + '-' + le.Name + '-' + curr.IsoCode, blng__PeriodStartDate__c = periodStart, blng__PeriodEndDate__c = periodEnd, blng__FinanceBook__c = fb.Id, blng__PeriodStatus__c = 'Open', blng__LegalEntity__c = le.Id, CurrencyIsoCode = curr.IsoCode);
                        blng__FinancePeriod__c fp = new blng__FinancePeriod__c(Name = String.valueOf(periodStart.year())+'.' + String.valueOf(periodStart.month())+'-' + fb.blng__PeriodType__c + '-' + le.Name + '-' + curr.IsoCode, blng__PeriodStartDate__c = periodStart, blng__PeriodEndDate__c = periodEnd, blng__FinanceBook__c = fb.Id, blng__PeriodStatus__c = 'Open', blng__LegalEntity__c = le.Id, CurrencyIsoCode = curr.IsoCode);

                        fpToInsert.add(fp);
                    }
                }
            }
        }

        insert fpToInsert;
    }

    //Revenue Distribution Methods
    @future
    public static void createRevenueTreatments() {
        List<blng__RevenueRecognitionTreatment__c> NewRevTreats = new List<blng__RevenueRecognitionTreatment__c>();
        List<blng__RevenueRecognitionTreatment__c> OldRevTreats = [SELECT 
                                                                         Name, blng__Active__c, 
                                                                         blng__FlatAmount__c, 
                                                                         blng__Notes__c, 
                                                                         blng__Percentage__c, 
                                                                         blng__ProcessingOrder__c, 
                                                                         blng__RevenueAgreementAssociation__c, 
                                                                         blng__RevenueDistributionMethod__c, blng__RevenueFinanceBook__c, 
                                                                         blng__RevenueGLRule__c, 
                                                                         blng__RevenueLegalEntity__c, 
                                                                         blng__RevenueRecognitionRule__c, blng__RevenueScheduleAmount__c, 
                                                                         blng__RevenueScheduleCreationAction__c, 
                                                                         blng__Type__c
                                                                   FROM blng__RevenueRecognitionTreatment__c ];

        for (Integer i = 0; i < OldRevTreats.size(); i++) {
            blng__RevenueRecognitionTreatment__c NewRev = OldRevTreats.get(i).clone(false, true);
            NewRevTreats.add(NewRev);
        }
        delete OldRevTreats;
        insert NewRevTreats;
        List<blng__TaxRate__c> NewTaxRate = new List<blng__TaxRate__c>();
        List<blng__TaxRate__c> OldTaxRate = [SELECT 
                                                   Name, blng__TaxCode__c, 
                                                   blng__State__c, 
                                                   blng__City__c, 
                                                   blng__Rate__c, 
                                                   blng__ZipCode__c, 
                                                   blng__Country__c, 
                                                   blng__LegalEntity__c, blng__Priority__c
                                             FROM blng__TaxRate__c ];

        for (Integer i = 0; i < OldTaxRate.size(); i++) {
            blng__TaxRate__c NewTR = OldTaxRate.get(i).clone(false, true);
            NewTaxRate.add(NewTR);
        }
        delete OldTaxRate;
        insert NewTaxRate;
    }

    public static void clearit() {
        List<blng__RevenueSchedule__c> deleteRS = [SELECT 
                                                         Id
                                                   FROM blng__RevenueSchedule__c ];
        delete deleteRS;
        List<blng__FinancePeriod__c> deleteFP = [SELECT 
                                                       Id
                                                 FROM blng__FinancePeriod__c ];
        delete deleteFP;
    }

    static void deleteFinancePeriods() {
        Map<Id, blng__FinancePeriod__c> fpMap = new Map<Id, blng__FinancePeriod__c>([SELECT 
                                                                                           Id
                                                                                     FROM blng__FinancePeriod__c ]);
        List<blng__FinancePeriod__c> deleteFp = fpMap.values();
        try {
            delete deleteFp;
        } catch (DmlException e) {
            System.debug(e);
            throw new AuraHandledException(e.getMessage());
        }
    }

    public static void deleteRevenueSchedules() {
        Map<Id, blng__RevenueSchedule__c> rsMap = new Map<Id, blng__RevenueSchedule__c>([SELECT 
                                                                                               Id
                                                                                         FROM blng__RevenueSchedule__c ]);
        List<blng__RevenueSchedule__c> deleteRs = rsMap.values();
        try {
            delete deleteRs;
        } catch (DmlException e) {
            System.debug(e);
            throw new AuraHandledException(e.getMessage());
        }
    }

    static void deleteRevenueTransactions() {
        Map<id, blng__RevenueTransaction__c> rtMap = new Map<id, blng__RevenueTransaction__c>([SELECT 
                                                                                                     Id
                                                                                               FROM blng__RevenueTransaction__c]);
        System.debug('Total rtMap size to delete: '+ rtMap.size() );
        for(Integer i = 0; i < rtMap.size(); i++){
            System.debug('Delete loop where i: ' + i);
            Map<id, blng__RevenueTransaction__c> rtMap2 = new Map<id, blng__RevenueTransaction__c>([SELECT 
                                                                                                     Id
                                                                                               FROM blng__RevenueTransaction__c LIMIT 1999]);
        	List<blng__RevenueTransaction__c> deleteRT2 = rtMap2.values();
        	try {
                System.debug('Attempting to delete ' + deleteRT2.size() + ' rt rows.');
           		delete deleteRT2;
        	} catch (DmlException e) {
            	System.debug(e);
            	throw new AuraHandledException(e.getMessage());
        	}
            
            rtMap2.clear();
            deleteRT2.clear();
        }
        
    }

    public class DeleteRecords implements Queueable {
        public void execute(QueueableContext context){
            //System.debug('Enqueue Limit : '+Limits.getQueueableJobs());
            //System.enqueueJob(new DeleteRevenueTransactions());
            System.debug('Enqueue Limit : '+Limits.getQueueableJobs());
            System.enqueueJob(new DeleteRevenueSchedules());
            System.debug('Enqueue Limit : '+Limits.getQueueableJobs());
            System.enqueueJob(new DeleteFinancePeriods());
        }
    }

    public class DeleteRevenueTransactions implements Queueable {
        private List<blng__RevenueTransaction__c> rtToDelete;

        public void getRevenueTransactions() {
            Map<Id, blng__RevenueTransaction__c> rtMap = new Map<Id, blng__RevenueTransaction__c>([SELECT 
                                                                                               Id
                                                                                         FROM blng__RevenueTransaction__c ]);
            this.rtToDelete = rtMap.values();
        }
        
        public void execute(QueueableContext context) {
            delete rtToDelete;
        }
    }
    
    public class DeleteRevenueSchedules implements Queueable {
        private List<blng__RevenueSchedule__c> rsToDelete;

        public void getRevenueSchedules() {
            Map<Id, blng__RevenueSchedule__c> rsMap = new Map<Id, blng__RevenueSchedule__c>([SELECT 
                                                                                               Id
                                                                                         FROM blng__RevenueSchedule__c ]);
            this.rsToDelete = rsMap.values();
        }
        
        public void execute(QueueableContext context) {
            delete rsToDelete;
        }
    }

    public class DeleteFinancePeriods implements Queueable {
        private List<blng__FinancePeriod__c> fps;

        public void getFinancePeriods() {
            Map<Id, blng__FinancePeriod__c> fpMap = new Map<Id, blng__FinancePeriod__c>([SELECT 
                                                                                               Id
                                                                                         FROM blng__FinancePeriod__c ]);
            this.fps = fpMap.values();
        }
        
        public void execute(QueueableContext context) {
            delete fps;
        }
    }
    
}