objects/blng__GLTreatment__c.object
<CustomObject>
    <fields>
        <fullName>blng__CreditGLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit GL Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>blng__GLAccount__c.blng__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>blng__GLAccount__c</referenceTo>
        <relationshipLabel>GL Treatments</relationshipLabel>
        <relationshipName>CreditGLTreatments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__DebitGLAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Debit GL Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>blng__GLAccount__c.blng__Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>blng__GLAccount__c</referenceTo>
        <relationshipLabel>GL Treatments</relationshipLabel>
        <relationshipName>DebitGLTreatments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>GL Treatment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GL Treatments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/blng__Invoice__c.object
<CustomObject>
    <description>Storing the Invoices.</description>
    <fields>
        <fullName>blng__Subtotal__c</fullName>
        <inlineHelpText>Invoice total (excluding tax)</inlineHelpText>
        <label>Subtotal</label>
        <summarizedField>blng__InvoiceLine__c.blng__Subtotal__c</summarizedField>
        <summaryForeignKey>blng__InvoiceLine__c.blng__Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>blng__TaxAmount__c</fullName>
        <inlineHelpText>Sum of all taxes for this invoice</inlineHelpText>
        <label>Tax</label>
        <summarizedField>blng__InvoiceLine__c.blng__TaxAmount__c</summarizedField>
        <summaryForeignKey>blng__InvoiceLine__c.blng__Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>blng__TotalAmount__c</fullName>
        <inlineHelpText>Invoice total (including tax). Equals SubTotal + Tax.</inlineHelpText>
        <label>Total Amount (With Tax)</label>
        <summarizedField>blng__InvoiceLine__c.blng__TotalAmount__c</summarizedField>
        <summaryForeignKey>blng__InvoiceLine__c.blng__Invoice__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/blng__InvoiceLine__c.object
<CustomObject>
    <description>The line items on Invoices, such as products etc.</description>
    <fields>
        <fullName>Account__c</fullName>
        <formula>blng__Invoice__r.blng__Account__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>blng__BillingFinanceBook__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Finance Book</label>
        <referenceTo>blng__FinanceBook__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>BillingFinanceBookInvoiceLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__BillingFinancePeriod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing Finance Period</label>
        <referenceTo>blng__FinancePeriod__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>BillingFinancePeriodInvoiceLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__BillingGLTreatment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Billing GL Treatment</label>
        <referenceTo>blng__GLTreatment__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>BillingGLTreatmentInvoiceLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__ChargeDate__c</fullName>
        <description>This is the date on which Invoice Line is Created</description>
        <label>Charge Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>blng__Invoice__c</fullName>
        <label>Invoice</label>
        <referenceTo>blng__Invoice__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>InvoiceInvoiceLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>blng__LegalEntity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Legal Entity</label>
        <referenceTo>blng__LegalEntity__c</referenceTo>
        <relationshipLabel>Invoice Lines</relationshipLabel>
        <relationshipName>LegalEntityInvoiceLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__Subtotal__c</fullName>
        <inlineHelpText>Invoice Line total (before taxes).</inlineHelpText>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>blng__TaxAmount__c</fullName>
        <inlineHelpText>Sum of all taxes for this invoice line</inlineHelpText>
        <label>Tax</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>blng__TaxGLTreatment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tax GL Treatment</label>
        <referenceTo>blng__GLTreatment__c</referenceTo>
        <relationshipLabel>Invoice Lines (Tax GL Treatment)</relationshipLabel>
        <relationshipName>TaxGLTreatmentInvoiceLines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>blng__TotalAmount__c</fullName>
        <inlineHelpText>SubTotal + Tax</inlineHelpText>
        <label>Total Amount (With Tax)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Line</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoice Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Transaction_Journal_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transaction Journal Entries</relationshipLabel>
        <relationshipName>Transaction_Journal_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Line</label>
        <referenceTo>blng__InvoiceLine__c</referenceTo>
        <relationshipLabel>Transaction Journal Entries</relationshipLabel>
        <relationshipName>Transaction_Journal_Entries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subtotal__c</fullName>
        <label>Subtotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice Line</fullName>
                </value>
                <value>
                    <fullName>Debit Note Line</fullName>
                </value>
                <value>
                    <fullName>Debit Note Line Allocation (Invoice Line)</fullName>
                </value>
                <value>
                    <fullName>Debit Note Line Allocation (Credit Note Line)</fullName>
                </value>
                <value>
                    <fullName>Credit Note Line</fullName>
                </value>
                <value>
                    <fullName>Credit Note Allocation</fullName>
                </value>
                <value>
                    <fullName>Revenue Transaction</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Payment Allocation (Invoice)</fullName>
                </value>
                <value>
                    <fullName>Payment Allocation (Invoice Line)</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Refund Line (Payment)</fullName>
                </value>
                <value>
                    <fullName>Refund Line (Credit Note Line)</fullName>
                </value>
                <value>
                    <fullName>Realized Gain/Loss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction Journal Entry</label>
    <nameField>
        <displayFormat>TJE-{000000}</displayFormat>
        <label>Transaction Journal Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Journal Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Transaction_Journal_Entry_Line__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transaction Journal Entry Lines</relationshipLabel>
        <relationshipName>Transaction_Journal_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice_Line__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice Line</label>
        <referenceTo>blng__InvoiceLine__c</referenceTo>
        <relationshipLabel>Transaction Journal Entry Lines</relationshipLabel>
        <relationshipName>Transaction_Journal_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Transaction_Journal_Entry__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction Journal Entry</label>
        <referenceTo>Transaction_Journal_Entry__c</referenceTo>
        <relationshipLabel>Transaction Journal Entry Lines</relationshipLabel>
        <relationshipName>Transaction_Journal_Entry_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Invoice Line</fullName>
                </value>
                <value>
                    <fullName>Debit Note Line</fullName>
                </value>
                <value>
                    <fullName>Debit Note Line Allocation (Invoice Line)</fullName>
                </value>
                <value>
                    <fullName>Debit Note Line Allocation (Credit Note Line)</fullName>
                </value>
                <value>
                    <fullName>Credit Note Line</fullName>
                </value>
                <value>
                    <fullName>Credit Note Allocation</fullName>
                </value>
                <value>
                    <fullName>Revenue Transaction</fullName>
                </value>
                <value>
                    <fullName>Payment</fullName>
                </value>
                <value>
                    <fullName>Payment Allocation (Invoice)</fullName>
                </value>
                <value>
                    <fullName>Payment Allocation (Invoice Line)</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Refund Line (Payment)</fullName>
                </value>
                <value>
                    <fullName>Refund Line (Credit Note Line)</fullName>
                </value>
                <value>
                    <fullName>Realized Gain/Loss</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Transaction Journal Entry Line</label>
    <nameField>
        <displayFormat>TJEL-{000000}</displayFormat>
        <label>Transaction Journal Entry Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transaction Journal Entry Lines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/transactionJournalEntryCreation.cls
// tony saarnio
// 2-13-2020

public class transactionJournalEntryCreation {
    
    @future(callout=true)   
    public static void CreateTransactionJournalEntries(Id invId){
        
        boolean debug = false;
        
        //instantiate list of journal entry and journal entry line objects
        List <Transaction_Journal_Entry__c> JEsToInsert = new List <Transaction_Journal_Entry__c> ();
        List <Transaction_Journal_Entry_Line__c> JELinesToInsert = new List <Transaction_Journal_Entry_Line__c> ();
        
        //query invoice line detail from invoice ID
        List <blng__InvoiceLine__c> invLines = [SELECT Id, 
                                                blng__Invoice__c,
                                                Account__c,
                                                blng__ChargeDate__c,
                                                blng__BillingFinanceBook__c,
                                                blng__BillingFinancePeriod__c,
                                                blng__LegalEntity__c,
                                                blng__TaxGLTreatment__c,
                                                blng__BillingGLTreatment__c,
                                                blng__Subtotal__c,
                                                blng__TaxAmount__c,
                                                blng__TotalAmount__c,
                                                blng__BillingGLTreatment__r.blng__CreditGLAccount__r.Id,
                                                blng__BillingGLTreatment__r.blng__DebitGLAccount__r.Id,
                                                blng__TaxGLTreatment__r.blng__CreditGLAccount__r.Id,
                                                blng__TaxGLTreatment__r.blng__DebitGLAccount__r.Id
                                                FROM blng__InvoiceLine__c WHERE blng__Invoice__c = :invId];
        
        
        if(debug){ system.debug(invId); }
        if(debug){ system.debug(invLines); }
        
        for(blng__InvoiceLine__c invLine : invLines){
            
            //instantiate the TJE object
            Transaction_Journal_Entry__c je = new Transaction_Journal_Entry__c(); 
            
            //map invoice line fields to new vehicle TJE object 
            je.Invoice_Line__c = invLine.Id;
            je.Account__c = invLine.Account__c;
            je.Transaction_Date__c = invLine.blng__ChargeDate__c;
            je.Transaction_Type__c = 'Invoice Line';
            je.Posting_Status__c = 'Drraft';
            je.Finance_Book__c = invLine.blng__BillingFinanceBook__c;
            je.Finance_Period__c = invLine.blng__BillingFinancePeriod__c;
            je.Legal_Entity__c = invLine.blng__LegalEntity__c;
            je.Tax_GL_Treatment__c = invLine.blng__TaxGLTreatment__c;
            je.Billing_GL_Treatment__c = invLine.blng__BillingGLTreatment__c;
            je.Subtotal__c = invLine.blng__Subtotal__c;
            je.Tax_Amount__c = invLine.blng__TaxAmount__c;
            //je.Total_CR__c = invLine.blng__TotalAmount__c;
            //je.Total_DR__c = invLine.blng__TotalAmount__c;
            je.Total_CR__c = invLine.blng__Subtotal__c;
            je.Total_DR__c = invLine.blng__Subtotal__c;
            je.Credit_GL_Account__c = invLine.blng__BillingGLTreatment__r.blng__CreditGLAccount__r.Id;
            je.Debit_GL_Account__c = invLine.blng__BillingGLTreatment__r.blng__DebitGLAccount__r.Id;
            je.Tax_Credit_GL_Account__c = invLine.blng__TaxGLTreatment__r.blng__CreditGLAccount__r.Id;
            je.Tax_Debit_GL_Account__c = invLine.blng__TaxGLTreatment__r.blng__DebitGLAccount__r.Id;
            
            //add new TJE to the list to be inserted.
            JEsToInsert.add(je);
        }
        
        // insert journal entries
        try {
            insert JEsToInsert; 
        } catch (system.Dmlexception e) {
            system.debug (e);
        }
        
        
        for(Transaction_Journal_Entry__c insertedJE : JEsToInsert){  
            
            //instantiate the TJELine objects
            Transaction_Journal_Entry_Line__c  jeLineCR = new Transaction_Journal_Entry_Line__c(); 
            Transaction_Journal_Entry_Line__c  jeLineDR = new Transaction_Journal_Entry_Line__c();
            Transaction_Journal_Entry_Line__c  jeLineCrTax = new Transaction_Journal_Entry_Line__c();
            Transaction_Journal_Entry_Line__c  jeLineDrTax = new Transaction_Journal_Entry_Line__c();
            
            //map TJE fields to new vehicle TJELine Credit object 
            jeLineCR.Account__c = insertedJE.Account__c;
            jeLineCR.Transaction_Journal_Entry__c = insertedJE.Id;
            jeLineCR.Invoice_Line__c = insertedJE.Invoice_Line__c;
            jeLineCR.Legal_Entity__c = insertedJE.Legal_Entity__c;
            jeLineCR.Finance_Book__c = insertedJE.Finance_Book__c;
            jeLineCR.Finance_Period__c = insertedJE.Finance_Period__c;
            jeLineCR.Journal_Entry_Line_Type__c = 'CR';
            jeLineCR.Transaction_Date__c = insertedJE.Transaction_Date__c;
            jeLineCR.Transaction_Type__c = 'Invoice Line';
            jeLineCR.Posting_Status__c = 'Draft';
            jeLineCR.Credit__c = insertedJE.Total_CR__c;
            jeLineCR.Transaction_Currency__c = 'USD';
            jeLineCR.Credit_GL_Account__c = insertedJE.Credit_GL_Account__c;
            jeLineCR.Debit_GL_Account__c = insertedJE.Debit_GL_Account__c ;
            
            //add new TJELine object to the list to be inserted.
            JELinesToInsert.add(jeLineCR);
            
            
            //map TJE fields to new vehicle TJELine Debit object
            jeLineDR.Account__c = insertedJE.Account__c;
            jeLineDR.Transaction_Journal_Entry__c = insertedJE.Id;
            jeLineDR.Invoice_Line__c = insertedJE.Invoice_Line__c;
            jeLineDR.Legal_Entity__c = insertedJE.Legal_Entity__c;
            jeLineDR.Finance_Book__c = insertedJE.Finance_Book__c;
            jeLineDR.Finance_Period__c = insertedJE.Finance_Period__c;
            jeLineDR.Journal_Entry_Line_Type__c = 'DR';
            jeLineDR.Transaction_Date__c = insertedJE.Transaction_Date__c;
            jeLineDR.Transaction_Type__c = 'Invoice Line';
            jeLineDR.Posting_Status__c = 'Draft';
            jeLineDR.Debit__c = insertedJE.Total_DR__c;
            jeLineDR.Transaction_Currency__c = 'USD';
            jeLineDR.Credit_GL_Account__c = insertedJE.Credit_GL_Account__c;
            jeLineDR.Debit_GL_Account__c = insertedJE.Debit_GL_Account__c ;
            
            //add new TJELine objects to the list to be inserted.
            JELinesToInsert.add(jeLineDR);
            
            
            if(insertedJE.Tax_Amount__c > 0){
                
                //map TJE fields to new vehicle TJELine CreditTax object if tax is applied
                jeLineCrTax.Account__c = insertedJE.Account__c;
                jeLineCrTax.Transaction_Journal_Entry__c = insertedJE.Id;
                jeLineCrTax.Invoice_Line__c = insertedJE.Invoice_Line__c;
                jeLineCrTax.Legal_Entity__c = insertedJE.Legal_Entity__c;
                jeLineCrTax.Finance_Book__c = insertedJE.Finance_Book__c;
                jeLineCrTax.Finance_Period__c = insertedJE.Finance_Period__c;
                jeLineCrTax.Journal_Entry_Line_Type__c = 'CR';
                jeLineCrTax.Transaction_Date__c = insertedJE.Transaction_Date__c;
                jeLineCrTax.Transaction_Type__c = 'Invoice Line';
                jeLineCrTax.Posting_Status__c = 'Draft';
                jeLineCrTax.Credit__c = insertedJE.Tax_Amount__c;
                jeLineCrTax.Transaction_Currency__c = 'USD';
                jeLineCrTax.Credit_GL_Account__c = insertedJE.Tax_Credit_GL_Account__c ;
                jeLineCrTax.Debit_GL_Account__c = insertedJE.Tax_Debit_GL_Account__c ;
                
                //add new TJELine objects to the list to be inserted.
                JELinesToInsert.add(jeLineCrTax);
            
        
                //map TJE fields to new vehicle TJELine DebitTax object if tax is applied
                jeLineDrTax.Account__c = insertedJE.Account__c;
                jeLineDrTax.Transaction_Journal_Entry__c = insertedJE.Id;
                jeLineDrTax.Invoice_Line__c = insertedJE.Invoice_Line__c;
                jeLineDrTax.Legal_Entity__c = insertedJE.Legal_Entity__c;
                jeLineDrTax.Finance_Book__c = insertedJE.Finance_Book__c;
                jeLineDrTax.Finance_Period__c = insertedJE.Finance_Period__c;
                jeLineDrTax.Journal_Entry_Line_Type__c = 'DR';
                jeLineDrTax.Transaction_Date__c = insertedJE.Transaction_Date__c;
                jeLineDrTax.Transaction_Type__c = 'Invoice Line';
                jeLineDrTax.Posting_Status__c = 'Draft';
                jeLineDrTax.Debit__c = insertedJE.Tax_Amount__c;
                jeLineDrTax.Transaction_Currency__c = 'USD';
                jeLineDrTax.Credit_GL_Account__c = insertedJE.Tax_Credit_GL_Account__c ;
                jeLineDrTax.Debit_GL_Account__c = insertedJE.Tax_Debit_GL_Account__c ;
                
                
                //add new TJELine objects to the list to be inserted.
                JELinesToInsert.add(jeLineDrTax);
            }
            
        }
        
        // insert journal entry lines
        try {
            insert JELinesToInsert; 
        } catch (system.Dmlexception f) {
            system.debug (f);
        }
    }
}