objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>End date for subscriptions in this group.</description>
        <inlineHelpText>End date for subscriptions in this group.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__DefaultSubscriptionTerm__c</fullName>
        <description>Term length of the subscription, which only applies if the product is a subscription. It is copied from the Subscription Term of the related product when the line item is first generated.</description>
        <inlineHelpText>Term length of the subscription, which only applies if the product is a subscription. It is copied from the Subscription Term of the related product when the line item is first generated.</inlineHelpText>
        <label>Default Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__EffectiveStartDate__c</fullName>
        <description>Effective start date for this subscription.</description>
        <formula>IF(ISBLANK(SBQQ__StartDate__c),
  IF(ISBLANK(SBQQ__Group__r.SBQQ__StartDate__c),SBQQ__Quote__r.SBQQ__StartDate__c,SBQQ__Group__r.SBQQ__StartDate__c),
  SBQQ__StartDate__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Effective start date for this subscription.</inlineHelpText>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>Date the service represented by this line item will end (only applies if product is a subscription).</description>
        <inlineHelpText>Date the service represented by this line item will end (only applies if product is a subscription).</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__NetPrice__c</fullName>
        <description>Net unit price for the product quoted by this line item.</description>
        <inlineHelpText>Net unit price for the product quoted by this line item.</inlineHelpText>
        <label>Net Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__NetTotal__c</fullName>
        <description>Net total price for this quote line item.</description>
        <formula>IF(AND(SBQQ__Renewal__c, !SBQQ__Existing__c, ISBLANK(SBQQ__PriorQuantity__c)), 0, SBQQ__NetPrice__c * SBQQ__EffectiveQuantity__c)</formula>
        <inlineHelpText>Net total price for this quote line item.</inlineHelpText>
        <label>Net Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProrateMultiplier__c</fullName>
        <description>Calculated ratio used to compute Prorated Price.</description>
        <inlineHelpText>Calculated ratio used to compute Prorated Price.</inlineHelpText>
        <label>Prorate Multiplier</label>
        <precision>8</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
        <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBQQ__Subscription__c.object
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Account that owns this subscription. This relationship is used for volume discount calculations.</description>
        <inlineHelpText>Account that owns this subscription. This relationship is used for volume discount calculations.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Contract__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contract that governs this subscription.</description>
        <inlineHelpText>Contract that governs this subscription.</inlineHelpText>
        <label>Contract</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__EndDate__c</fullName>
        <description>The last date this contract is valid.</description>
        <formula>if ( ISBLANK (SBQQ__SubscriptionEndDate__c), SBQQ__Contract__r.EndDate, SBQQ__SubscriptionEndDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The last date this contract is valid.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SBQQ__NetPrice__c</fullName>
        <description>Net price for this subscription.</description>
        <inlineHelpText>Net price for this subscription.</inlineHelpText>
        <label>Net Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product used to sell this subscription.</description>
        <inlineHelpText>Product used to sell this subscription.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__ProrateMultiplier__c</fullName>
        <description>Calculated ratio used to compute prorated price.</description>
        <inlineHelpText>Calculated ratio used to compute prorated price.</inlineHelpText>
        <label>Prorate Multiplier</label>
        <precision>8</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity of this subscription product purchased by the customer.</description>
        <inlineHelpText>Quantity of this subscription product purchased by the customer.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__QuoteLine__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote line that generated this subscription.</description>
        <inlineHelpText>Quote line that generated this subscription.</inlineHelpText>
        <label>Quote Line</label>
        <referenceTo>SBQQ__QuoteLine__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>The first date this subscription is in effect.</description>
        <formula>if ( ISBLANK (SBQQ__SubscriptionStartDate__c), SBQQ__Contract__r.StartDate, SBQQ__SubscriptionStartDate__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The first date this subscription is in effect.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/q2c_waterFallController.cls
public class q2c_waterFallController{
    public Id Acct {get; set;}
    public Id Quote {get; set;}
    public Date StartDate {get; set;}
    public Decimal ExistingMRR {get; set;}
    public Decimal NetNewMRR {get; set;}
    public Decimal ExpansionMRR {get; set;} 
    public Decimal ChurnMRR {get; set;}
    public Decimal EndingMRR {get; set;}
    public Decimal QuotedMRR {get; set;} 
    public Decimal SubMRR {get; set;}
    public Decimal UpliftMRR {get; set;}
    public Decimal ExpansionFromRamp {get; set;}
    public Decimal ExpansionFromAddon {get; set;}
    
    public q2c_waterFallController(){
        this.Acct = ApexPages.currentPage().getParameters().get('Account');
        this.Quote = ApexPages.currentPage().getParameters().get('Quote');
        this.StartDate = Date.valueof(ApexPages.currentPage().getParameters().get('StartDate'));

        getMRRData();
    }
    
    private void getMRRData(){
        Date EndDate=this.StartDate.addDays(-1);
        //EXISTING MRR
        List<SBQQ__Subscription__c> ExistingMRRSubscriptions = [SELECT SBQQ__Product__c, SBQQ__EndDate__c, SBQQ__StartDate__c, SBQQ__Quantity__c, SBQQ__ProrateMultiplier__c, SBQQ__QuoteLine__r.SBQQ__DefaultSubscriptionTerm__c, SBQQ__NetPrice__c FROM SBQQ__Subscription__c WHERE  SBQQ__Account__c = :this.Acct AND SBQQ__Contract__r.Status = 'Activated'];
        List<SBQQ__Subscription__c> RenewableSubscriptions = new List<SBQQ__Subscription__c>();
        List<SBQQ__Subscription__c> ActiveSubscriptions = new List<SBQQ__Subscription__c>();
        
        for(SBQQ__Subscription__c ExistSub:ExistingMRRSubscriptions){
            if((ExistSub.SBQQ__EndDate__c >= EndDate) && (ExistSub.SBQQ__StartDate__c <= EndDate)){
                RenewableSubscriptions.add(ExistSub);
            }if((ExistSub.SBQQ__EndDate__c >= this.StartDate) && (ExistSub.SBQQ__StartDate__c <= this.StartDate)){
                ActiveSubscriptions.add(ExistSub);
            }
        }
            
        Decimal ExistingMRRagg = 0;
        
        Decimal UpliftMRR = 0;
        for(SBQQ__Subscription__c ExistSub: ExistingMRRSubscriptions){
            if(ExistSub.SBQQ__StartDate__c<= EndDate && ExistSub.SBQQ__EndDate__c>= EndDate){
                ExistingMRRagg+= (ExistSub.SBQQ__Quantity__c*ExistSub.SBQQ__NetPrice__c/(ExistSub.SBQQ__ProrateMultiplier__c*ExistSub.SBQQ__QuoteLine__r.SBQQ__DefaultSubscriptionTerm__c));
            }
        }
        // NETNEW + Expansion
        List<SBQQ__QuoteLine__c> MRRQuoteLines = [SELECT SBQQ__Product__c, SBQQ__Quantity__c, SBQQ__EffectiveStartDate__c, SBQQ__ProrateMultiplier__c,SBQQ__DefaultSubscriptionTerm__c, SBQQ__NetTotal__c FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c =:Quote AND SBQQ__DefaultSubscriptionTerm__c >0];        
        List<SBQQ__QuoteLine__c> StartMRRQuoteLines = new List<SBQQ__QuoteLine__c>();
        
        for(SBQQ__QuoteLine__c Ql: MRRQuoteLines){
            if(Ql.SBQQ__EffectiveStartDate__c == StartDate){
                StartMRRQuoteLines.add(Ql);
            }
        }
        
        Set<Id> setProds= new Set <Id>();
        List<Id> UniqueProdList = new List<Id>();
        for(SBQQ__QuoteLine__c QL :MRRQuoteLines){
            setProds.add(QL.SBQQ__Product__c);
        }
        UniqueProdList.addAll(setProds);

        Set<Id> setSubs= new Set <Id>();
        List<Id> UniqueSubList = new List<Id>();
        for(SBQQ__Subscription__c QL :ExistingMRRSubscriptions){
            setSubs.add(QL.SBQQ__Product__c);
        }
        UniqueSubList.addAll(setSubs);
        system.debug(UniqueProdList);
        system.debug(UniqueSubList);
        system.debug(StartDate);
        system.debug('debug');


      
        List<Id> LiveSubscriptions = New List<Id>();
        for (SBQQ__Subscription__c Sub : ExistingMRRSubscriptions){
            LiveSubscriptions.add(Sub.SBQQ__Product__c);
        }
        Decimal NetNewMRRagg = 0;      
        
        for(SBQQ__QuoteLine__c QL :MRRQuoteLines){
            if(!hasSub(QL.SBQQ__Product__c, LiveSubscriptions)){
                    NetNewMRRagg+=QL.SBQQ__NetTotal__c/(QL.SBQQ__ProrateMultiplier__c*QL.SBQQ__DefaultSubscriptionTerm__c);
            }
        }
        //ExpansionMRRagg = ExpansionFromRamp+ExpansionFromAddon
        Decimal ExpansionMRRagg = 0;
        Decimal ExpansionFromRamp = 0;
        Decimal ExpansionFromAddon = 0;
        //Map<Id, Decimal, Decimal> Product = new Map<Id, Decimal, Decimal>();
        //EXPANSION MRR we want the increase of currently held products.  two types of expansion MRR (add-on(quote start date < subscription end date) and ramp(quote startdate > subscription end date THIS ONE NEEDS TO BE COMPARED TO EXPIRING SUBSCRIPTION TOTALS))
            for(Id QuotedProd:UniqueProdList){
                Decimal QuotedMRR = 0;
                Decimal SubMRR = 0;
                Decimal QuotedQty = 0;
                Decimal SubQty = 0;

               for(SBQQ__QuoteLine__c QL : MRRQuoteLines ){//loop unique quoted product        
                    if(Ql.SBQQ__Product__c == QuotedProd && UniqueSubList.contains(QuotedProd)){
                        system.debug('Quoted MRR '+ QL.SBQQ__Product__c);
                        QuotedMRR +=QL.SBQQ__NetTotal__c/(QL.SBQQ__ProrateMultiplier__c*QL.SBQQ__DefaultSubscriptionTerm__c);
                        system.debug('Quoted MRR '+ QuotedMRR);
                        QuotedQty+=QL.SBQQ__Quantity__c;
                    }
               }
               for(SBQQ__Subscription__c Sub : ActiveSubscriptions){//loop unique quoted product   
                   
                    if(Sub.SBQQ__Product__c == QuotedProd){
                            system.debug('Quoted MRR '+ Sub.SBQQ__Product__c);
                        
                            QuotedMRR +=Sub.SBQQ__Quantity__c*Sub.SBQQ__NetPrice__c/(Sub.SBQQ__ProrateMultiplier__c*Sub.SBQQ__QuoteLine__r.SBQQ__DefaultSubscriptionTerm__c);
                            system.debug('Quoted MRR '+ SubMRR);
                            QuotedQty+=Sub.SBQQ__Quantity__c;
                       
                        }
                    }
               
               for(SBQQ__Subscription__c Sub : RenewableSubscriptions){//loop unique quoted product   
                   
                    if(Sub.SBQQ__Product__c == QuotedProd){
                        system.debug('Subbed MRR '+ Sub.SBQQ__Product__c);
                    
                        SubMRR +=Sub.SBQQ__Quantity__c*Sub.SBQQ__NetPrice__c/(Sub.SBQQ__ProrateMultiplier__c*Sub.SBQQ__QuoteLine__r.SBQQ__DefaultSubscriptionTerm__c);
                        system.debug('Subbed MRR '+ SubMRR);
                        SubQty+=Sub.SBQQ__Quantity__c;
                       
                    }
                }
                   
                    if(QuotedMRR>SubMRR && SubMRR>0){ 
                        ExpansionFromRamp+=QuotedMRR-SubMRR;
                        if((QuotedMRR/QuotedQty) > (SubMRR/SubQty)){
                            UpliftMRR+= ((QuotedMRR/QuotedQty) - (SubMRR/SubQty))*(SubQty);
                        }
                    }
            }
        ExpansionMRRagg=ExpansionFromRamp+ExpansionFromAddon-UpliftMRR;
        //ENDING MRR
        //We need to aggregagate this quote and all the subscriptions live at the startdate
        //
        Decimal EndingMRR=0;
        Decimal ChurnMRR=0;
        for(SBQQ__Subscription__c Sub : ActiveSubscriptions){
            EndingMRR+=Sub.SBQQ__Quantity__c*Sub.SBQQ__NetPrice__c/(Sub.SBQQ__ProrateMultiplier__c*Sub.SBQQ__QuoteLine__r.SBQQ__DefaultSubscriptionTerm__c);   
        }
        for(SBQQ__QuoteLine__c QL : StartMRRQuoteLines){
            EndingMRR+=QL.SBQQ__NetTotal__c/(QL.SBQQ__ProrateMultiplier__c*QL.SBQQ__DefaultSubscriptionTerm__c);
        }
        //CHURN MRR the difference        
        ChurnMRR= EndingMRR-(ExistingMRRagg+NetNewMRRagg+ExpansionMRRagg+UpliftMRR);
        system.debug('ENDINGMRR'+EndingMRR);
        system.debug('EX+NN+EXP'+(ExistingMRRagg+NetNewMRRagg+ExpansionMRRagg));
        system.debug('EXPANSION'+(ExpansionMRRagg));
               
                

            
        
        //ENDING MRR This is all MRR from this quote added to any live subscriptions at the start date
        this.QuotedMRR=QuotedMRR;
        this.SubMRR=SubMRR;
        this.ExpansionFromRamp=ExpansionFromRamp;
        this.ExpansionFromAddon=ExpansionFromAddon;
        
        this.UpliftMRR = Math.Round(UpliftMRR*100.00)/100.00;
        this.ExistingMRR = Math.Round(ExistingMRRagg*100.00)/100.00;
        this.NetNewMRR =Math.Round(NetNewMRRagg*100.00)/100.00;
        this.ExpansionMRR = Math.Round(ExpansionMRRagg*100.00)/100.00;
        this.ChurnMRR = Math.Round(ChurnMRR*100.00)/100.00;
        this.EndingMRR = Math.Round(EndingMRR*100.00)/100.00;
    }
    
    public boolean hasSub(Id qlProduct, List<Id> SubProdIds){
        for(Id QL : SubProdIds){
            if(qlProduct==QL){
                return true;
            }
        }
        return false;
    }
}