objects/Contract.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Quote from which this Contract was created.</description>
        <inlineHelpText>Quote from which this Contract was created.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Contracts</relationshipLabel>
        <relationshipName>Contracts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order.object
<CustomObject>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The quote where the order is created from.</description>
        <inlineHelpText>The quote where the order is created from.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SBQQ__AssetAmendmentBehavior__c</fullName>
        <description>Indicates how assets representing this product behave on amendments.</description>
        <inlineHelpText>Select a behavior when amending assets representing this product. By default, asset quantities cannot decrease unless an upgrade is added, and no refund is applied.</inlineHelpText>
        <label>Asset Amendment Behavior</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Default</fullName>
                    <default>true</default>
                    <label>Default</label>
                </value>
                <value>
                    <fullName>Allow Refund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionPricing__c</fullName>
        <description>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</description>
        <inlineHelpText>Type of pricing to use for this subscription. &quot;None&quot; means this product is not a subscription.</inlineHelpText>
        <label>Subscription Pricing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>Percent Of Total</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quantity__c</fullName>
        <description>Quantity being quoted.</description>
        <inlineHelpText>Quantity being quoted.</inlineHelpText>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionPricing__c</fullName>
        <description>Method of calculating the subscription price. A blank value indicates that the line item isn&apos;t a subscription product.</description>
        <inlineHelpText>Indicates how the subscription price is calculated. If this is blank, the line items is not a subscription product.</inlineHelpText>
        <label>Subscription Pricing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Fixed Price</fullName>
                </value>
                <value>
                    <fullName>Percent Of Total</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContractViewCtrl.cls
/**
 * Created by scheck on 8/6/18.
 */

public class ContractViewCtrl {
    @AuraEnabled
    public static List<Contract> getContracts() {

        Id contactId = [SELECT ContactId FROM User WHERE Id =: UserInfo.getUserId()].ContactId;
        System.debug('Contact Id: ');
        System.debug(contactId);
        Id accId  = [SELECT AccountId FROM Contact WHERE Id =: contactId].AccountId;
        System.debug('Account Id: ');
        System.debug(accId);
        return [SELECT
                Id,
                AccountId,
                ContractNumber,
                Status,
                StartDate,
                EndDate,
                ContractTerm
        FROM Contract
        WHERE AccountId =: accId
        ORDER BY ContractNumber ASC];
    }


    @AuraEnabled
    public static Id fireAmend(String contractId) {
        System.debug('inside fireAmend');
        System.debug('Amending: ' + contractId);

        String quoteModelJSON = SBQQ.ServiceRouter.load('SBQQ.ContractManipulationAPI.ContractAmender', contractId, null);
        cQuoteModel qModel = (cQuoteModel)JSON.deserialize(quoteModelJSON, cQuoteModel.class);
        System.debug(qModel);

        return qModel.record.Id;
    }


    @AuraEnabled
    public static Id fireCancel(String contractId) {
        System.debug('inside fireCancel');
        System.debug('Cancelling: ' + contractId);

        String quoteModelJSON = SBQQ.ServiceRouter.load('SBQQ.ContractManipulationAPI.ContractAmender', contractId, null);
        cQuoteModel qModel = (cQuoteModel)JSON.deserialize(quoteModelJSON, cQuoteModel.class);
        System.debug(qModel);

        List<SBQQ__QuoteLine__c> qLines = [SELECT
                Id,
                SBQQ__Quote__c,
                SBQQ__Quantity__c,
                SBQQ__Product__c,
                SBQQ__Product__r.SBQQ__AssetAmendmentBehavior__c,
                SBQQ__Product__r.SBQQ__SubscriptionPricing__c,
                SBQQ__Product__r.Name
        FROM SBQQ__QuoteLine__c
        WHERE SBQQ__Quote__c =: qModel.record.Id];

        List<SBQQ__QuoteLine__c> updates = new List<SBQQ__QuoteLine__c>();
        for (SBQQ__QuoteLine__c qLine : qLines){
            qLine.SBQQ__Quantity__c = 0;
            updates.add(qLine);
        }
        System.debug('Lines to Insert: ');
        System.debug(JSON.serializePretty(updates));

        try {
            Database.update(updates);
            System.debug('Zeroed out QuoteLines and updated');
        } catch (DmlException e) {
            System.debug('Error zeroing out QuoteLines: ' + e);

        }


        return qModel.record.Id;
    }


    @AuraEnabled
    public static Boolean isRendered(){
        Boolean isRendered = true;
        if (UserInfo.getUserType() == 'Guest') {
            isRendered = false;
        }
        return isRendered;
    }

}