objects/Inventory__c.object
<CustomObject>
    <fields>
        <fullName>Inventory_Status__c</fullName>
        <label>Inventory Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Out of Stock</fullName>
                </value>
                <value>
                    <fullName>Low Stock</fullName>
                </value>
                <value>
                    <fullName>Sufficient Stock</fullName>
                </value>
                <value>
                    <fullName>Extra Stock</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Manufacturing_Site__c</fullName>
        <label>Manufacturing Site</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Fort Lauderdale</fullName>
                </value>
                <value>
                    <fullName>Los Angeles</fullName>
                </value>
                <value>
                    <fullName>New York</fullName>
                </value>
                <value>
                    <fullName>Pittsburgh</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <formula>Product__r.ProductCode</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Inventory</relationshipLabel>
        <relationshipName>Inventory</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity_Allocated__c</fullName>
        <label>Quantity Allocated</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Assigned__c</fullName>
        <label>Quantity Assigned</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Available__c</fullName>
        <label>Quantity Available</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_On_Hand__c</fullName>
        <label>Quantity On Hand</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Cost__c</fullName>
        <label>Unit Cost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/InventoryController.cls
public class InventoryController {
    public List<Inventory__c> invs { get; set; }
    public String productCodeParam = ApexPages.currentPage().getParameters().get('r');
    public Integer invTotal = 0;
    public String hardware = 'false';
    
    
    // Return a list of data points for a chart
    public List<Data> getData() {
        return InventoryController.getChartData();
    }
  
    public InventoryController(){
    	invs = [select Manufacturing_Site__c, Quantity_Allocated__c, Quantity_Assigned__c, Quantity_Available__c, Quantity_On_Hand__c, Inventory_Status__c, Unit_Cost__c, Unit_Price__c, Product_Code__c, Product__c FROM Inventory__c where Product_Code__c  =: productCodeParam];
        invTotal = invs.size();
        if(invTotal > 0) {
            hardware = 'true';
        }
        System.debug('Inventory Total:' + invTotal);
        System.debug('Inventory:' + invs);
    }
    
    // Make the chart data available via JavaScript remoting
    //@RemoteAction
    //public static List<Data> getRemoteData() {
    //    return InventoryController.getChartData();
   // }

    // The actual chart data; needs to be static to be
    // called by a @RemoteAction method

		public static List<Data> getChartData()
        {
        List<Data> data = new List<Data>();
				data.add(new Data('Jan', 'Chicago', 5, 'Fort Lauderdale', 10, 'Los Angeles', 20, 'New York', 10, 'Pittsburgh', 10));
				data.add(new Data('Feb', 'Chicago', 15, 'Fort Lauderdale', 5, 'Los Angeles', 5, 'New York', 10, 'Pittsburgh', 25));
				data.add(new Data('Mar', 'Chicago', 15, 'Fort Lauderdale', 5, 'Los Angeles', 5, 'New York', 15, 'Pittsburgh', 5));
				data.add(new Data('Apr', 'Chicago', 20, 'Fort Lauderdale', 5, 'Los Angeles', 5, 'New York', 10, 'Pittsburgh', 10));

				return data;
        }


    // Wrapper class
    public class Data
    {
        public String mon { get; set; }
        public String c_chi { get; set; }
        public String c_ftl { get; set; }
        public String c_lax { get; set; }
        public String c_nyc { get; set; }
        public String c_ptb { get; set; }

        public Integer chi { get; set; }
        public Integer ftl { get; set; }
        public Integer lax { get; set; }
        public Integer nyc { get; set; }
        public Integer ptb { get; set; }

        public Data(String mon, String c_chi, Integer chi, String c_ftl, Integer ftl, String c_lax, Integer lax, String c_nyc, Integer nyc, String c_ptb, Integer ptb)
        {
            this.mon = mon;
            this.c_chi = c_chi;
			this.chi = chi;

            this.c_ftl = c_ftl;
            this.ftl = ftl;

            this.c_lax = c_lax;
            this.lax = lax;

            this.c_nyc = c_nyc;
            this.nyc = nyc;

            this.c_ptb = c_ptb;
            this.ptb = ptb;
        }
    }
}