objects/Opportunity.object
<CustomObject>
    <recordTypes>
        <fullName>CPQ</fullName>
        <active>true</active>
        <businessProcess>Order Management</businessProcess>
        <label>CPQ</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SBQQ__SubscriptionTerm__c</fullName>
        <description>Term length of this subscription. Only applicable if the product is a subscription.</description>
        <inlineHelpText>Term length of this subscription. Only applicable if the product is a subscription.</inlineHelpText>
        <label>Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__CustomAction__c.object
<CustomObject>
    <customHelpPage>SBQQ__CustomActionsHelp</customHelpPage>
    <description>Custom action definition.</description>
    <fields>
        <fullName>SBQQ__EventHandlerName__c</fullName>
        <description>Method name for the click handler of this custom action.</description>
        <inlineHelpText>Method name for the click handler of this custom action.</inlineHelpText>
        <label>Event Handler Name</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>UI element that this custom action is rendered as.</description>
        <inlineHelpText>UI element that this custom action is rendered as.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>Menu</fullName>
                </value>
                <value>
                    <fullName>Separator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Custom Action</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__ProductFeature__c.object
<CustomObject>
    <customHelpPage>SBQQ__ProductFeatureHelp</customHelpPage>
    <description>Feature of a configurable product that consists of one or more options. Features are configured by selecting one or more options.</description>
    <label>Product Feature</label>
    <nameField>
        <label>Feature Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Features</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__ProductOption__c.object
<CustomObject>
    <customHelpPage>SBQQ__ProductOptionHelp</customHelpPage>
    <description>Option for a configurable product.</description>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>Type of this option.</description>
        <inlineHelpText>Use &quot;Component&quot; if this option, including quantity, is dependent on parent. Use&quot; Accessory&quot; if this option is dependent on parent but quantity is independent. Use &quot;Related Product&quot; for related but fully independent products.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Component</fullName>
                    <default>true</default>
                    <label>Component</label>
                </value>
                <value>
                    <fullName>Accessory</fullName>
                </value>
                <value>
                    <fullName>Related Product</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product Option</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionTerm__c</fullName>
        <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
        <inlineHelpText>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</inlineHelpText>
        <label>Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>Indicates the type of quote.</description>
        <inlineHelpText>Indicates the type of quote.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote</fullName>
                    <default>true</default>
                    <label>Quote</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Re-Quote</fullName>
                </value>
                <value>
                    <fullName>eCommerce Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <recordTypes>
        <fullName>CPQ</fullName>
        <active>true</active>
        <label>CPQ</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/qtc_PreviewConfigCTRL.cls
/**
 * Created by scheck on 10/25/18.
 * CPQ Product Models packaged interally
 */

public with sharing class qtc_PreviewConfigCTRL {

    @AuraEnabled
    public static String getProductString(Id productId){

        List<Product2> productList = [
                SELECT
                        Id, (SELECT
                            UnitPrice,
                            Pricebook2.IsStandard,
                            Pricebook2.Name,
                            Pricebook2.Id,
                            Pricebook2.CurrencyIsoCode,
                            CurrencyIsoCode
                    FROM PricebookEntries
                    WHERE Pricebook2.IsStandard = TRUE AND Pricebook2.CurrencyIsoCode = 'USD')
                FROM Product2 WHERE Id =: productId];

        List<PricebookEntry> pbes = new List<PricebookEntry>();

        //This record will now have the correct type to be added to the list
        pbes.add(productList[0].PricebookEntries[0]);
        Id standardPricebookId = pbes[0].Pricebook2.Id;
        String currencyCode = pbes[0].Pricebook2.CurrencyIsoCode;

        // Use CPQ APIs to read in product from Id, Pricebook Id and Currency Code.
        PreviewProductReader reader = new PreviewProductReader();
        PreviewProductModel product = reader.read(productId,standardPricebookId,currencyCode);
        System.debug(product);
        String productString = JSON.serializePretty(product);


        return productString;
    }

    @AuraEnabled
    public static String getConfigURL(Id productId){

        // Get the Add Products Custom Action
        Id customActionId = [
                SELECT
                        Id,
                        SBQQ__EventHandlerName__c
                FROM SBQQ__CustomAction__c
                WHERE SBQQ__EventHandlerName__c = 'onAddProducts'
                LIMIT 1].Id;

        // Insert Test Opp
        Opportunity opp = new Opportunity(CloseDate = Date.today(),
                StageName = 'Qualification',
                Name = 'Opportunity');

        Database.insert(opp);

        // Insert Test Quote
        SBQQ__Quote__c q = new SBQQ__Quote__c(SBQQ__Opportunity2__c=opp.Id,
                SBQQ__Primary__c = true,
                SBQQ__SubscriptionTerm__c = 12,
                SBQQ__Status__c = 'Draft',
                SBQQ__Type__c = 'Quote');

        Database.insert(q);

        // add the aloha redirect to stay in lightning
        String configURL = '/one/one.app#/alohaRedirect/apex/sbqq__sb?scontrolCaching=1&id=' + q.id + '&scontrolCaching=1#/product/pc?qId=' + q.Id + '&aId=' + customActionId + '&pId=' + productId + '&redirectUrl=LineEditor&open=0';

        return configURL;

    }

    /*
    *  Create all models needed for Product API privately
    */

    // Reader class to load model from Salesforce CPQ API
    private class PreviewProductReader {
        private PreviewProductModel read(Id productId, Id pricebookId, String currencyCode) {
            ProductReaderContext ctx = new ProductReaderContext(pricebookId, currencyCode);
            String productJSON = SBQQ.ServiceRouter.load('SBQQ.ProductAPI.ProductLoader', productId, JSON.serialize(ctx));
            return (PreviewProductModel) JSON.deserialize(productJSON, PreviewProductModel.class);
        }
    }
    
    // Product Reader Context (pricebook + currency code)
    private class ProductReaderContext {
        private Id pricebookId;
        private String currencyCode;

        private ProductReaderContext(Id pricebookId, String currencyCode) {
            this.pricebookId = pricebookId;
            this.currencyCode = currencyCode;
        }
    }

    // Product Model
    private class PreviewProductModel {
        private Product2 record;
        private Id upgradedAssetId;
        private String currencySymbol;
        private String currencyCode;
        private String[] featureCategories;
        private PreviewOptionModel[] options;
        private PreviewFeatureModel[] features;
        private PreviewConfigurationModel configuration;
        private PreviewConfigAttributeModel[] configurationAttributes;
        private PreviewConfigAttributeModel[] inheritedConfigurationAttributes;
        private PreviewConstraintModel[] constraints;

    }

    // Feature Model
    private class PreviewFeatureModel {
        private SBQQ__ProductFeature__c record;
        private String instructionsText;
        private Boolean containsUpgrades;

    }

    // Option Model
    private class PreviewOptionModel {
        private SBQQ__ProductOption__c record;
        private Map<String,String> externalConfigurationData;
        private Boolean configurable;
        private Boolean configurationRequired;
        private Boolean quantityEditable;
        private Boolean priceEditable;
        private Decimal productQuantityScale;
        private Boolean priorOptionExists;
        private Set<Id> dependentIds;
        private Map<String,Set<Id>> controllingGroups;
        private Map<String,Set<Id>> exclusionGroups;
        private String reconfigureDimensionWarning;
        private Boolean hasDimension;
        private Boolean isUpgrade;
        private String dynamicOptionKey;

    }


    // Constraint Model
    private class PreviewConstraintModel {
        private SBQQ__OptionConstraint__c record;
        private Boolean priorOptionExists;

    }

    // Configuration Model
    private class PreviewConfigurationModel {
        private Id configuredProductId;
        private Id optionId;
        private SBQQ__ProductOption__c optionData; // Editable data about the option in question, such as quantity or discount
        private SBQQ__ProductOption__c configurationData;
        private SBQQ__ProductOption__c inheritedConfigurationData;
        private PreviewConfigurationModel[] optionConfigurations;
        private Boolean configured;
        private Boolean changedByProductActions;
        private Boolean isDynamicOption;
        private Boolean isUpgrade;
        private Set<Id> disabledOptionIds;
        private Set<Id> hiddenOptionIds;
        private Decimal listPrice;
        private Boolean priceEditable;
        private String[] validationMessages;
        private String dynamicOptionKey;

    }

    // Configuration Attribute Model
    private class PreviewConfigAttributeModel {
        private String name;
        private String targetFieldName;
        private Decimal displayOrder;
        private String colmnOrder;
        private Boolean required;
        private Id featureId;
        private String position;
        private Boolean appliedImmediately;
        private Boolean applyToProductOptions;
        private Boolean autoSelect;
        private String[] shownValues;
        private String[] hiddenValues;
        private Boolean hidden;
        private String noSuchFieldName;
        private Id myId;

    }
}