objects/Product2.object
<CustomObject>
    <fields>
        <fullName>SBQQ__SubscriptionTerm__c</fullName>
        <description>Term length of this subscription. Only applicable if the product is a subscription.</description>
        <inlineHelpText>Term length of this subscription. Only applicable if the product is a subscription.</inlineHelpText>
        <label>Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__CustomAction__c.object
<CustomObject>
    <customHelpPage>SBQQ__CustomActionsHelp</customHelpPage>
    <description>Custom action definition.</description>
    <fields>
        <fullName>SBQQ__Action__c</fullName>
        <description>Action that this custom action performs.</description>
        <inlineHelpText>Action that this custom action performs.</inlineHelpText>
        <label>Action</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SBQQ__Location__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Add Products</fullName>
                </value>
                <value>
                    <fullName>Add Favorites</fullName>
                </value>
                <value>
                    <fullName>Upgrade Assets</fullName>
                </value>
                <value>
                    <fullName>Renew Subscriptions</fullName>
                </value>
                <value>
                    <fullName>Save</fullName>
                </value>
                <value>
                    <fullName>Quick Save</fullName>
                </value>
                <value>
                    <fullName>Cancel</fullName>
                </value>
                <value>
                    <fullName>Calculate</fullName>
                </value>
                <value>
                    <fullName>Delete Lines</fullName>
                </value>
                <value>
                    <fullName>Add Group</fullName>
                </value>
                <value>
                    <fullName>Ungroup</fullName>
                </value>
                <value>
                    <fullName>Add Solution Group</fullName>
                </value>
                <value>
                    <fullName>Reset Discounts</fullName>
                </value>
                <value>
                    <fullName>Optional: All</fullName>
                </value>
                <value>
                    <fullName>Optional: None</fullName>
                </value>
                <value>
                    <fullName>Clone Group</fullName>
                </value>
                <value>
                    <fullName>Delete Group</fullName>
                </value>
                <value>
                    <fullName>Add To Favorites</fullName>
                </value>
                <value>
                    <fullName>Remove From Favorites</fullName>
                </value>
                <value>
                    <fullName>Delete Line</fullName>
                </value>
                <value>
                    <fullName>Clone Line</fullName>
                </value>
                <value>
                    <fullName>Reconfigure Line</fullName>
                </value>
                <value>
                    <fullName>Desegment Line</fullName>
                </value>
                <value>
                    <fullName>Resegment Line</fullName>
                </value>
                <value>
                    <fullName>View Discount Schedule</fullName>
                </value>
                <value>
                    <fullName>Launch External</fullName>
                </value>
                <value>
                    <fullName>Clone with Related</fullName>
                </value>
                <value>
                    <fullName>Create Order</fullName>
                </value>
                <value>
                    <fullName>Edit Lines</fullName>
                </value>
                <value>
                    <fullName>Generate Document</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>UI element that this custom action is rendered as.</description>
        <inlineHelpText>UI element that this custom action is rendered as.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Button</fullName>
                </value>
                <value>
                    <fullName>Menu</fullName>
                </value>
                <value>
                    <fullName>Separator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Custom Action</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Status__c</fullName>
        <description>Status indicating where quote is in its lifecycle.</description>
        <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>In Review</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Presented</fullName>
                </value>
                <value>
                    <fullName>Accepted</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SBQQ__SubscriptionTerm__c</fullName>
        <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
        <inlineHelpText>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</inlineHelpText>
        <label>Subscription Term</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SBQQ__Type__c</fullName>
        <description>Indicates the type of quote.</description>
        <inlineHelpText>Indicates the type of quote.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote</fullName>
                    <default>true</default>
                    <label>Quote</label>
                </value>
                <value>
                    <fullName>Renewal</fullName>
                </value>
                <value>
                    <fullName>Amendment</fullName>
                </value>
                <value>
                    <fullName>Re-Quote</fullName>
                </value>
                <value>
                    <fullName>eCommerce Request</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Q2Cpreviewconfig.cls
public class Q2Cpreviewconfig {
    public Product2 Prod;
  
    public Q2Cpreviewconfig(ApexPages.StandardController controller) {
        Prod = (Product2) controller.getRecord();
        
    }

   public PageReference preview(){
        Id CustomAction = [SELECT Id FROM SBQQ__CustomAction__c WHERE SBQQ__Action__c = 'Add Products' LIMIT 1].Id;
        Opportunity opp = new Opportunity(CloseDate = Date.today(), StageName = 'Qualification', Name = 'Opportunity');
        Database.insert(opp);
        SBQQ__Quote__c q = new SBQQ__Quote__c(SBQQ__Opportunity2__c=Opp.Id, SBQQ__Primary__c = true, SBQQ__SubscriptionTerm__c = 12, SBQQ__Status__c = 'Draft', SBQQ__Type__c = 'Quote');
        insert q;
        return new PageReference('/apex/sbqq__sb?scontrolCaching=1&id=' + q.id + '&scontrolCaching=1#/product/pc?qId=' + q.Id + '&aId=' + CustomAction + '&pId=' + Prod.Id + '&redirectUrl=LineEditor&open=0');
    }
}