objects/sbaa__Approval__c.object
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <fields>
        <fullName>CreditNote__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Credit Note</label>
        <referenceTo>blng__CreditNote__c</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreditNoteExtController.cls
public with sharing class CreditNoteExtController {
	private Id recordId;
	public CreditNoteExtController(ApexPages.StandardController stdController) {
		recordId = stdController.getId();
	}
	public PageReference onSubmit() {
		if (recordId != null) {
			SBAA.ApprovalAPI.submit(recordId, SBAA__Approval__c.CreditNote__c);
		}
		return new PageReference('/' + recordId);
	}
	public PageReference onRecall() {
		if (recordId != null) {
			SBAA.ApprovalAPI.recall(recordId, SBAA__Approval__c.CreditNote__c);
		}
		return new PageReference('/' + recordId);
	}
}