objects/sbaa__Approval__c.object
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <fields>
        <fullName>Finance_Period__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finance Period</label>
        <referenceTo>blng__FinancePeriod__c</referenceTo>
        <relationshipLabel>Approvals</relationshipLabel>
        <relationshipName>Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/FinPeriodExtController.cls
public with sharing class FinPeriodExtController {
    private Id finPerId;
    public FinPeriodExtController(ApexPages.StandardController stdController) {
        finPerId = stdController.getId();
    }
    public PageReference onSubmit() {
        if (finPerId != null) {
            SBAA.ApprovalAPI.submit(finPerId, SBAA__Approval__c.Finance_Period__c);
        }
        return new PageReference('/' + finPerId);
    }
    public PageReference onRecall() {
        if (finPerId != null) {
            SBAA.ApprovalAPI.recall(finPerId, SBAA__Approval__c.Finance_Period__c);
        }
        return new PageReference('/' + finPerId);
    }
}