objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Cost_Hidden__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cost Hidden</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__UnitCost__c</fullName>
        <description>Cost for one unit of product quoted on this line item.</description>
        <inlineHelpText>Cost for one unit of product quoted on this line item.</inlineHelpText>
        <label>Unit Cost</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>All_Costs_Visible__c</fullName>
        <defaultValue>false</defaultValue>
        <label>All Costs Visible</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/DemoPageSecurityPlugin.cls
global class DemoPageSecurityPlugin implements SBQQ.PageSecurityPlugin, SBQQ.PageSecurityPlugin2 {
    private Boolean isCostUser { get; set; }

    global DemoPageSecurityPlugin() {
        User currentUser = [SELECT Id, All_Costs_Visible__c FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1];
        this.isCostUser = currentUser.All_Costs_Visible__c;

    }

    global Boolean isFieldEditable(String page, Schema.SObjectField field) {
        System.debug('***METHOD CALLED: isFieldEditable(String, Field');
        System.debug('***STRING PASSED: ' + page);
        System.debug('***FIELD PASSED: ' + String.valueOf(field));
        return null;
    }

    global Boolean isFieldEditable(String page, Schema.SObjectField field, SObject obj) {
        System.debug('***METHOD CALLED: isFieldEditable(String, Field, Object');
        System.debug('***STRING PASSED: ' + page);
        System.debug('***FIELD PASSED: ' + String.valueOf(field));
        System.debug('***OBJECT PASSED: ' + String.valueOf(obj));
        return null;
    }

    global Boolean isFieldVisible(String page, Schema.SObjectField field) {
        System.debug('***METHOD CALLED: isFieldVisible(String, Field');
        System.debug('***STRING PASSED: ' + page);
        System.debug('***FIELD PASSED: ' + String.valueOf(field));
        return null;
    }

    global Boolean isFieldVisible(String page, Schema.SObjectField field, SObject obj) {
        System.debug('***METHOD CALLED: isFieldVisible(String, Field, Object');
        System.debug('***STRING PASSED: ' + page);
        System.debug('***FIELD PASSED: ' + String.valueOf(field));
        System.debug('***OBJECT PASSED: ' + String.valueOf(obj));
        if (field == SBQQ__QuoteLine__c.SBQQ__UnitCost__c) {
            SBQQ__QuoteLine__c line = (SBQQ__QuoteLine__c) obj;
            Boolean isCostHidden = line.Cost_Hidden__c;
            return (this.isCostUser || !isCostHidden);
        }

        return null;
    }
}