objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Start date for subscriptions in this quote.</description>
        <inlineHelpText>Start date for subscriptions in this quote.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>SBQQ__Discount__c</fullName>
        <description>Additional customer discount extended for this line item expressed in terms of percentage.</description>
        <inlineHelpText>Additional customer discount extended to this line item expressed in form of a percentage.</inlineHelpText>
        <label>Additional Disc. (%)</label>
        <precision>11</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SBQQ__Incomplete__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Flag set internally by application logic when a line is saved to an incomplete database. This may happen when price rules are evaluated. Test this field in validation rules to avoid them firing prematurely. Do NOT add to page layout or otherwise update.</description>
        <inlineHelpText>Flag set internally by application logic when a line is saved to an incomplete database. This may happen when price rules are evaluated. Test this field in validation rules to avoid them firing prematurely. Do NOT add to page layout or otherwise update.</inlineHelpText>
        <label>Incomplete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__StartDate__c</fullName>
        <description>Date the service represented by this line item will begin (only applies if product is a subscription).</description>
        <inlineHelpText>The date the subscription for this product begins.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Q2C_DataCannon.cls
public class Q2C_DataCannon {

    /**
    Known Limitations
    -No amendments/renewals
    -opp stages is not dynamic
    -not using discounts
    Use lookup field from object that looks up to quote
	Public Opportunity Opp {get;set;}
    **/

    public static void copyQuote(String quotetocopy, Date startDate, Date endDate, Integer numRecords, Decimal AverageDisc) {
        //get accounts up to number needed (limit numRecords)
        List<Account> acc = new List<Account>();
        acc = [SELECT Id FROM Account LIMIT :numRecords];
        //Create Opportunities
        //SBQQ.TriggerControl.disable();
        List<Opportunity> newOpps = new List<Opportunity>();
        for (Integer i = 0; i < numRecords; i++) {
            Opportunity Opp = new Opportunity(Name = 'Opp Cannon ' + String.valueOf(i + 1));    // Set new Opps
            Integer myInt = Math.floor(Math.random() * startDate.daysBetween(endDate)).intValue();
            Opp.StageName = stagePicker(i, 3, 2, 1, 1, 1, 1, 2, 3);
            Opp.CloseDate = startDate.addDays(myInt);
            Integer a = Math.mod(i, acc.size());
            Opp.AccountId = acc.get(a).Id;
            newOpps.add(Opp);
        }
        Database.insert(newOpps);

        //SBQQ.TriggerControl.enable();
        List<SBQQ__Quote__c> Myquote = new List <SBQQ__Quote__c>();
        List<SBQQ__Quote__c> newQuotes = new List<SBQQ__Quote__c>();

        SObjectType objToken = Schema.getGlobalDescribe().get('SBQQ__Quote__c');
        DescribeSObjectResult objDef = objToken.getDescribe();
        Map<String, SObjectField> fields = objDef.fields.getMap();
        List<String> fieldslist = new List<String>();
        for (String s : fields.keySet()) {
            fieldslist.add(s);
        }
        String qq = 'SELECT ' + String.join(fieldslist, ',') + ' FROM SBQQ__Quote__c WHERE Id=:quotetocopy';
        System.debug(qq);
        Myquote = Database.query(qq);


        for (Integer i = 0; i < numRecords; i++) {
            SBQQ__Quote__c Quote = Myquote.get(0).clone(false, true); //set new quotes
            Quote.SBQQ__StartDate__c = newOpps.get(i).CloseDate.addDays(1);
            Quote.SBQQ__Opportunity2__c = newOpps.get(i).Id;
            Quote.SBQQ__Account__c = newOpps.get(i).Account.Id;
            Quote.SBQQ__Primary__c = false;
            newQuotes.add(Quote);
        }

        Database.insert(newQuotes);
        //SBQQ.TriggerControl.disable();

        List<SBQQ__QuoteLine__c> QLtoCopy = new List<SBQQ__QuoteLine__c>();

        SObjectType objToken1 = Schema.getGlobalDescribe().get('SBQQ__QuoteLine__c');
        DescribeSObjectResult objDef1 = objToken1.getDescribe();
        Map<String, SObjectField> fields1 = objDef1.fields.getMap();
        List<String> fieldslist1 = new List<String>();
        for (String s1 : fields1.keySet()) {
            fieldslist1.add(s1);
        }
        String q = 'SELECT ' + String.join(fieldslist1, ',') + ' FROM SBQQ__QuoteLine__c WHERE SBQQ__Quote__c=:quotetocopy';
        System.debug(q);
        QLtoCopy = Database.query(q);

        List<SBQQ__QuoteLine__c> newQuoteLines = new List<SBQQ__QuoteLine__c>();

        for (Integer i = 0; i < numRecords; i++) { //through each quote (i)
            for (Integer j = 0; j < QLtoCopy.size(); j++) { //through each quoteline (j)
                SBQQ__QuoteLine__c QuoteLine = QLtoCopy.get(j).clone(false, true);
                //Decimal origDiscount=QLtoCopy.get(j).SBQQ__Discount__c*(1+0.25)*(2*Math.random()-1);
                QuoteLine.SBQQ__Discount__c = Math.abs(AverageDisc * (2 * Math.random()));
                QuoteLine.SBQQ__Quote__c = newQuotes.get(i).Id;
                QuoteLine.SBQQ__Incomplete__c = true;

                newQuoteLines.add(QuoteLine);
            }
        }

        Database.insert(newQuoteLines);
        // SBQQ.TriggerControl.enable();


        for (Integer i = 0; i < numRecords; i++) {
            newQuotes.get(i).SBQQ__Primary__c = true;
        }

        update newQuotes;


        List <Opportunity> ClosedOpps = new List<Opportunity>();
        ClosedOpps = [SELECT Id, StageName FROM Opportunity WHERE StageName = 'Finalizing Closure'];
        for (Integer i = 0; i < ClosedOpps.size(); i++) {
            ClosedOpps.get(i).StageName = 'Closed Won';
        }

        update ClosedOpps;

        //update newOpps;

        /**for(integer i =0; i<numRecords;i++){
             // Set new Opps
            NewOpps.get(i).StageName=randomizer.getRandomPicklistValue(NewOpps.get(i),'StageName',true);
        }
        database.update(newOpps);**/
    }

    public static String stagePicker(Integer numi, Integer num1, Integer num2, Integer num3, Integer num4, Integer num5, Integer num6, Integer num7, Integer num8) {
        Integer sumNum = num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8;
        if (Math.mod(numi + 1, sumNum) >= 0 && Math.mod(numi, sumNum) < num1) {
            return 'Qualification';
        } else if (Math.mod(numi + 1, sumNum) >= num1 && Math.mod(numi, sumNum) < num1 + num2) {
            return 'Needs Analysis';
        } else if (Math.mod(numi + 1, sumNum) >= num2 && Math.mod(numi, sumNum) < num1 + num2 + num3) {
            return 'Value Proposition';
        } else if (Math.mod(numi + 1, sumNum) >= num3 && Math.mod(numi, sumNum) < num1 + num2 + num3 + num4) {
            return 'Proposal/Price Quote';
        } else if (Math.mod(numi + 1, sumNum) >= num4 && Math.mod(numi, sumNum) < num1 + num2 + num3 + num4 + num5) {
            return 'Negotiation/Review';
        } else if (Math.mod(numi + 1, sumNum) >= num5 && Math.mod(numi, sumNum) < num1 + num2 + num3 + num4 + num5 + num6) {
            return 'Finalizing Closure';
        } else if (Math.mod(numi + 1, sumNum) >= num6 && Math.mod(numi, sumNum) < num1 + num2 + num3 + num4 + num5 + num6 + num7) {
            return 'Finalizing Closure';
        } else if (Math.mod(numi + 1, sumNum) >= num7 && Math.mod(numi, sumNum) < sumNum) {
            return 'Closed Lost';
        } else {
            return'Qualification';
        }
    }
}