objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Opportunity2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity associated with this Quote.</description>
        <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Q2Cacceptcustomerquote.cls
public class Q2Cacceptcustomerquote {

    //Public String Name  {get;set;}
// This is an Extension Controller. Thus, we must invoke the standard controller.
    public Q2Cacceptcustomerquote(ApexPages.StandardController controller) {
    }

// Method for creating Quote 
    public PageReference genOpp() {
        SBQQ__Quote__c Quote = [SELECT Id FROM SBQQ__Quote__c WHERE Id =:ApexPages.currentPage().getParameters().get('id')];
    
        String Name = [SELECT SBQQ__Account__r.name FROM SBQQ__Quote__c WHERE Id =:ApexPages.currentPage().getParameters().get('id')].SBQQ__Account__r.name;
        Id Acct = [SELECT SBQQ__Account__c FROM SBQQ__Quote__c WHERE Id =:ApexPages.currentPage().getParameters().get('id')].SBQQ__Account__c;
    
       Opportunity NewOpp = New Opportunity(Name = 'Customer Self Service Quote for ' + Name ,StageName='Qualification', CloseDate = Date.Today(), AccountId=Acct);
       insert NewOpp;
       Quote.SBQQ__Opportunity2__c = NewOpp.Id;
       Quote.SBQQ__Primary__c= True;
       update Quote;
    return new PageReference('/'+NewOpp.Id);
}
}