objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The customer account for this quote. Defaulted to the account for the opportunity when quote is created.</description>
        <inlineHelpText>The customer account for this quote. Defaults to the account for the opportunity when creating a quote.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SBQQ__QuoteLine__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <fields>
        <fullName>Approval__c</fullName>
        <formula>IF( Text(SBQQ__PricingMethod__c) &lt;&gt; &quot;Cost&quot; &amp;&amp; SBQQ__AdditionalDiscount__c == 0.0,&quot;&quot;, 
IF( ApprovalLevel__c = 0, (IMAGE(&apos;http://i.imgur.com/JhCARqi.png&apos;,&quot;&quot;,30,30)+&quot; OK&quot;), 
IF( ApprovalLevel__c = 1, (IMAGE(&apos;http://i.imgur.com/ACrfXdO.png&apos;,&quot;&quot;,30,30)+&quot; Manager&quot;), 
IF( ApprovalLevel__c = 2, (IMAGE(&apos;http://i.imgur.com/IwqGy9p.png&apos;,&quot;&quot;,30,30)+&quot; Director&quot;),
IF( ApprovalLevel__c = 3, (IMAGE(&apos;http://i.imgur.com/mBBmLRl.png&apos;,&quot;&quot;,30,30)+&quot; VP&quot;), &quot;&quot;)))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_Term_Price__c</fullName>
        <formula>IF( SBQQ__ProrateMultiplier__c = 0 || SBQQ__Quantity__c = 0,
NULL,
(SBQQ__NetTotal__c / SBQQ__ProrateMultiplier__c ) / ( SBQQ__Quantity__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Term Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__CustomerPrice__c</fullName>
        <description>Customer unit price for the product quoted by this line item. This is the Net Unit Price excluding any partner discounts.</description>
        <inlineHelpText>Customer unit price for the product quoted by this line item. This is the Net Unit Price excluding any partner discounts.</inlineHelpText>
        <label>Customer Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__ListPrice__c</fullName>
        <description>List unit price for the product quoted by this line item. List Price originates from the price book.</description>
        <inlineHelpText>List unit price for the product quoted by this line item. List Price originates from the price book.</inlineHelpText>
        <label>List Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__NetPrice__c</fullName>
        <description>Net unit price for the product quoted by this line item.</description>
        <inlineHelpText>Net unit price for the product quoted by this line item.</inlineHelpText>
        <label>Net Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product quoted by this line item.</description>
        <inlineHelpText>Product quoted by this line item.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>R00N70000001lXB6EAM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SBQQ__Quote__c</fullName>
        <description>Quote to which this line item belongs.</description>
        <inlineHelpText>Quote to which this line item belongs.</inlineHelpText>
        <label>Quote</label>
        <referenceTo>SBQQ__Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>LineItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__TotalDiscountRate__c</fullName>
        <description>Total discount for this line item including volume discount, contracted discount, and additional discount.</description>
        <formula>IF(SBQQ__ProratedListPrice__c == 0, 0,
IF(ISPICKVAL(SBQQ__DiscountScheduleType__c, &apos;Slab&apos;) &amp;&amp; NOT(SBQQ__Existing__c),
IF(SBQQ__Quantity__c == 0, 0, (SBQQ__ProratedListPrice__c * SBQQ__Quantity__c - SBQQ__CustomerPrice__c) / (SBQQ__Quantity__c * SBQQ__ProratedListPrice__c)),
IF(ISPICKVAL(SBQQ__DiscountScheduleType__c, &apos;Slab&apos;) &amp;&amp; SBQQ__Existing__c,
IF(SBQQ__Quantity__c == SBQQ__PriorQuantity__c, 0, (SBQQ__ProratedListPrice__c * (SBQQ__Quantity__c-SBQQ__PriorQuantity__c) - SBQQ__CustomerPrice__c) / ((SBQQ__Quantity__c-SBQQ__PriorQuantity__c) * SBQQ__ProratedListPrice__c)),
(SBQQ__ProratedListPrice__c - SBQQ__CustomerPrice__c) / SBQQ__ProratedListPrice__c)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Total discount for this line item including volume discount, contracted discount, and additional discount.</inlineHelpText>
        <label>Total Discount (%)</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SBQQ__UnitCost__c</fullName>
        <description>Cost for one unit of product quoted on this line item.</description>
        <inlineHelpText>Cost for one unit of product quoted on this line item.</inlineHelpText>
        <label>Unit Cost</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Standalone_Selling_Total_Price__c</fullName>
        <formula>Base_SSP__c *  SBQQ__Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Standalone Selling Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Threshold_1_Amount__c</fullName>
        <formula>SBQQ__SpecialPrice__c - (SBQQ__SpecialPrice__c * Threshold_1_Level__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Threshold 1 Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Threshold_2_Amount__c</fullName>
        <formula>SBQQ__SpecialPrice__c - (SBQQ__SpecialPrice__c * Threshold_2_Level__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Threshold 2 Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Threshold_3_Amount__c</fullName>
        <formula>SBQQ__SpecialPrice__c - (SBQQ__SpecialPrice__c * Threshold_3_Level__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Threshold 3 Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/qtcEinsteinAnalyzerController.cls
public class qtcEinsteinAnalyzerController{
    public Id qLine {get;set;}
    public Id productId {get; set;}
    public boolean isDone {get; set;}
    public SBQQ__QuoteLine__c ql {get;set;}
    public Product2 productObj {get; set;}    
    public String getFg(){
        return null;
    }
    public Decimal lp {get; set;}
    public Decimal net {get; set;}
    public Decimal cp {get;set;}
    public Decimal uc {get;set;}
    public Decimal ssp {get;set;}
    public Decimal ntp {get;set;}
    public Decimal lev1 {get;set;}
    public Decimal lev2 {get;set;}
    public Decimal lev3 {get;set;}
    public String app {get;set;}


    
    public qtcEinsteinAnalyzerController(){
        this.isDone = false; //true will not display Analytics & standard should be false!
        try{
            qLine = ApexPages.currentPage().getParameters().get('Id');
        } catch(Exception e){
            this.isDone = true;
            //qLine = 'a0h3c00000bPDp0AAG';
            system.debug('Error caught, no value for qLine. qLine was not written into memory.');
        }
        //qLine = ApexPages.currentPage().getParameters().get('Id'); // ISSUE IS HERE.. null breaks every time
        //system.debug('qLine: ' + qLine);
        
        if (this.isDone == false) {
            system.debug('inside condition, this.isDone: ' + this.isDone);
            system.debug('qLine: ' + qLine);
        //String strId = Id.valueOf(qLine); // switch to compare value with string = ''

            ql = [SELECT Id, SBQQ__Product__c, SBQQ__ListPrice__c, SBQQ__Quote__r.SBQQ__Account__r.Name,
                        SBQQ__NetPrice__c, SBQQ__TotalDiscountRate__c, SBQQ__CustomerPrice__c, SBQQ__UnitCost__c, Standalone_Selling_Total_Price__c, Net_Term_Price__c, Threshold_1_Amount__c, Threshold_2_Amount__c, Threshold_3_Amount__c, Approval__c                                
                        FROM SBQQ__QuoteLine__c
                        WHERE Id =: qLine].get(0);
            system.debug('inside isDone condition, scripts are running');
            getProdId();
            getProdObj();
            lp = ql.SBQQ__ListPrice__c;
            net = ql.SBQQ__NetPrice__c;
            cp = ql.SBQQ__CustomerPrice__c;
            uc = ql.SBQQ__UnitCost__c;
            ssp = ql.Standalone_Selling_Total_Price__c;
            ntp = ql.Net_Term_Price__c;
            lev1 = ql.Threshold_1_Amount__c;
            lev2 = ql.Threshold_2_Amount__c;
            lev3 = ql.Threshold_3_Amount__c; 
            app = ql.Approval__c;
        }
    }

    public Id getProdId(){
        productId = [SELECT Id, Name, SBQQ__Product__c, SBQQ__ListPrice__c, 
                        SBQQ__NetPrice__c, SBQQ__UnitCost__c, SBQQ__CustomerPrice__c
                        FROM SBQQ__QuoteLine__c
                        WHERE Id =: qLine].get(0).SBQQ__Product__c;

        return productId;
    }


    public Product2 getProdObj(){
        productObj = [SELECT Id, Name FROM Product2 WHERE Id =: productId].get(0);

        return productObj;
    }

        
}