objects/SBQQ__Quote__c.object
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <fields>
        <fullName>SBQQ__Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox which if checked designates the quote as the Primary Quote</description>
        <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/priceRuleExecutor.cls
global class priceRuleExecutor implements Database.Batchable<SObject> {

    global final Set<String> quIds;
    global String qlQuery;

    global priceRuleExecutor(Set<String> quoteIdSet) {
        quIds = quoteIdSet;
        qlQuery = 'SELECT id FROM SBQQ__Quote__c WHERE id IN: quIds';
    }

    global Database.QueryLocator start(Database.BatchableContext info) {
        return Database.getQueryLocator(qlQuery);
    }

    global void execute(Database.BatchableContext info, List<SBQQ__Quote__c> scope) {
        List<SBQQ__Quote__c> qsToUpdate = new List<SBQQ__Quote__c>();
        for (SBQQ__Quote__c s : scope) {
            s.SBQQ__Primary__c = true;
            qsToUpdate.add(s);
        }
        try {
            update qsToUpdate;
        } catch (Exception e) {
            System.debug('ERROR Price Rule Trigger Failed. Exception: ' + e);
        }
    }

    global void finish(Database.BatchableContext info) {
        System.debug('priceRuleExecutor Finished');
    }
}