objects/SBQQ__ContractedPrice__c.object
<CustomObject>
    <customHelpPage>SBQQ__ContractedPriceHelp</customHelpPage>
    <description>Contracted (negotiated) price for a product for a given customer account.</description>
    <fields>
        <fullName>SBQQ__Account__c</fullName>
        <description>Account for which this price was negotiated.</description>
        <inlineHelpText>Account for which this price was negotiated.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracted Prices</relationshipLabel>
        <relationshipName>R00N70000001olI5EAI</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SBQQ__Discount__c</fullName>
        <description>Discount off the list price (percent) represented by this Contracted Price. Either this field or Price should be set but not both.</description>
        <inlineHelpText>Discount off the Price Book price (percent) represented by this Contracted Price. Either this field or Price should be set but not both.</inlineHelpText>
        <label>Discount</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>SBQQ__Price__c</fullName>
        <description>Actual price that was negotiated. This value will override any other price such as the one from a price book or a volume-discounted price.</description>
        <inlineHelpText>Enter the price that has been negotiated with the customer. This value will override any other price such as the one from a price book or a volume-discounted price.</inlineHelpText>
        <label>Price</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SBQQ__Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Product for which this price was negotiated.</description>
        <inlineHelpText>Select a product from any price book that you want to apply to this discount.</inlineHelpText>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Contracted Prices</relationshipLabel>
        <relationshipName>ContractedPrices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contracted Price</label>
    <nameField>
        <displayFormat>CP-{00000}</displayFormat>
        <label>Contracted Price Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contracted Prices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Q2CAccountHierarchyController.cls
public with sharing class Q2CAccountHierarchyController {
    public Account acc { get; private set; }
    public List<Account> accountList { get; private set; }
    public ApexPages.StandardController controller { get; private set; }
    public Q2CAccountHierarchyController(ApexPages.StandardController controller) {
        this.acc = (Account)controller.getRecord();
        this.accountList = new List<Account>();
        
        Id TopParent=GetTopLevleElement(acc.Id);
        
        Account baseAccount = [SELECT Id, 
                               ParentId, 
                               Name,
                               Parent.Name,
                                (SELECT Id, SBQQ__Product__c, SBQQ__Price__c, SBQQ__Discount__c FROM SBQQ__R00N70000001olI5EAI__r),
                               (SELECT Id, Name FROM ChildAccounts)
                               FROM Account 
                               WHERE Id = :TopParent];
        accountList.add(baseAccount);
        // Traverse the hierarchy downwards
        Set<Id> accountsToQuery = new Map<Id, Account>(baseAccount.ChildAccounts).keySet();
        while (accountsToQuery.size() > 0) {
            List<Account> thisLevelAccounts = [SELECT Id, Name, Parent.Name,
                                               (SELECT Id, SBQQ__Product__c, SBQQ__Price__c, SBQQ__Discount__c FROM SBQQ__R00N70000001olI5EAI__r),
                                               (SELECT Id, Name FROM ChildAccounts)
                                               FROM Account
                                               WHERE Id IN :accountsToQuery];
            accountsToQuery = new Set<Id>();
            for (Account a : thisLevelAccounts) {
                // Add this Account (with its Contacts) to the list.
                accountList.add(a);
                // Add this Account's children to the query for the next level.
                for (Account child : a.ChildAccounts) {
                    accountsToQuery.add(child.Id);
                }
            }
        }
    }
    public String GetTopLevleElement( String objId ){
        Boolean topLevelParent = false;
        while ( !topLevelParent ) {
            Account a = [ Select Id, ParentId From Account where Id =: objId limit 1 ];
            if ( a.ParentID != null ) {
                objId = a.ParentID;
            }
            else {
                topLevelParent = true;
            }
        }
        return objId ;
    }
}